### ISSUE TITLE
x509.Certificate has no subjectPublicKey

### ISSUE THREAD

**Issue by spike-spb** [wbond/asn1crypto#120]
```python
pub_key = cert['tbs_certificate']['subject_public_key_info']['public_key']
```

an error:
```bash
Traceback (most recent call last):
  File "/home/user/work/cades-asn1crypto/sign.py", line 285, in <module>
    ocsp_req = make_ocsp_request(ca_cert)
  File "/home/user/work/cades-asn1crypto/sign.py", line 69, in make_ocsp_request
    issuer_key_hash = cert['tbs_certificate']['subject_public_key_info']['public_key']
  File "/home/user/work/asn1crypto/asn1crypto/core.py", line 3248, in __getitem__
    self._parse_children()
  File "/home/user/work/asn1crypto/asn1crypto/core.py", line 3619, in _parse_children
    cls._precomputed_specs[field] or self._determine_spec(field))
  File "/home/user/work/asn1crypto/asn1crypto/core.py", line 3475, in _determine_spec
    spec_override = callback(self)
  File "/home/user/work/asn1crypto/asn1crypto/keys.py", line 985, in _public_key_spec
    }[algorithm]
KeyError: '1.2.643.2.2.19'
```

```bash
$ openssl x509 -in data/usercert.pem -text -noout
Subject Public Key Info:
            Public Key Algorithm: GOST R 34.10-2001
            Unable to load Public Key
140132291471256:error:0609E09C:digital envelope routines:PKEY_SET_TYPE:unsupported algorithm:p_lib.c:239:
140132291471256:error:0B07706F:x509 certificate routines:X509_PUBKEY_get:unsupported algorithm:x_pubkey.c:148:
```

With some patches openssl understands it: https://www.altlinux.org/%D0%93%D0%9E%D0%A1%D0%A2_%D0%B2_OpenSSL (in russian).
[usercert.tar.gz](https://github.com/wbond/asn1crypto/files/2465208/usercert.tar.gz)

**Comment by wbond** [comment]
The OID 1.2.643.2.2.19 appears to identify gostR3410-2001. https://tools.ietf.org/html/rfc4357.html

Someone would have to make a PR that added that OID and related ASN.1 definitions around https://github.com/wbond/asn1crypto/blob/master/asn1crypto/keys.py#L924-L989.

**Comment by ikirtyanov** [comment]
Hi @krash84 
I've had the similar issue and solved by editing keys.py, added 1 string to class PublicKeyAlgorithmId(ObjectIdentifier)
'1.2.643.7.1.1.1.1': 'gost',

```
class PublicKeyAlgorithmId(ObjectIdentifier):
    """
    Original Name: None
    Source: https://tools.ietf.org/html/rfc3279
    """

    _map = {
        # https://tools.ietf.org/html/rfc3279#page-19
        '1.2.840.113549.1.1.1': 'rsa',
        # https://tools.ietf.org/html/rfc3447#page-47
        '1.2.840.113549.1.1.7': 'rsaes_oaep',
        # https://tools.ietf.org/html/rfc4055#page-8
        '1.2.840.113549.1.1.10': 'rsassa_pss',
        # https://tools.ietf.org/html/rfc3279#page-18
        '1.2.840.10040.4.1': 'dsa',
        # https://tools.ietf.org/html/rfc3279#page-13
        '1.2.840.10045.2.1': 'ec',
        # https://tools.ietf.org/html/rfc3279#page-10
        '1.2.840.10046.2.1': 'dh',
	'1.2.643.7.1.1.1.1': 'gost',
    }

```

And 1 string to class PublicKeyInfo(Sequence):
'gost': (ECPointBitString, None),

```
class PublicKeyInfo(Sequence):
    """
    Original Name: SubjectPublicKeyInfo
    Source: https://tools.ietf.org/html/rfc5280#page-17
    """

    _fields = [
        ('algorithm', PublicKeyAlgorithm),
        ('public_key', ParsableOctetBitString),
    ]

    def _public_key_spec(self):
        algorithm = self['algorithm']['algorithm'].native
        return {
            'rsa': RSAPublicKey,
            'rsaes_oaep': RSAPublicKey,
            'rsassa_pss': RSAPublicKey,
            'dsa': Integer,
            # We override the field spec with ECPoint so that users can easily
            # decompose the byte string into the constituent X and Y coords
            'ec': (ECPointBitString, None),
            'dh': Integer,
            'gost': (ECPointBitString, None),
        }[algorithm]

    _spec_callbacks = {
        'public_key': _public_key_spec
    }

```
