### ISSUE TITLE
Cannot extract pubkey from certificate

### ISSUE THREAD

**Issue by ftbarata** [wbond/asn1crypto#127]
I have this code below working, but:
1) I'm unable to read pubkey from the generated certificate. AFAIK, a certificate is composed by some elements, including signature algorithm, public key and the signature itself, so anyone could verify the signature using same algorithm and the pubkey, right? I tried 
```
openssl x509 -pubkey -noout -in cert.pem 
Error getting public key
140003854860736:error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag:../crypto/asn1/tasn_dec.c:1129:
140003854860736:error:0D06C03A:asn1 encoding routines:asn1_d2i_ex_primitive:nested asn1 error:../crypto/asn1/tasn_dec.c:693:
140003854860736:error:0D08303A:asn1 encoding routines:asn1_template_noexp_d2i:nested asn1 error:../crypto/asn1/tasn_dec.c:626:Field=n, Type=RSA
140003854860736:error:0408B004:rsa routines:rsa_pub_decode:RSA lib:../crypto/rsa/rsa_ameth.c:51:
140003854860736:error:0B09407D:x509 certificate routines:x509_pubkey_decode:public key decode error:../crypto/x509/x_pubkey.c:124:
```

Code:
```
            try:
                for token in lib.get_tokens():
                    if token.serial.decode() == TOKEN_SERIAL:
                        with token.open(user_pin=PIN) as session:
                            priv = ''
                            pub = ''
                            try:
                                # priv = session.get_key(object_class=pkcs11.constants.ObjectClass.PRIVATE_KEY, label=TOKEN_LABEL)
                                priv = session.get_key(object_class=pkcs11.constants.ObjectClass.PRIVATE_KEY)
                            except pkcs11.exceptions.NoSuchKey:
                                for j in session.get_objects({Attribute.CLASS: ObjectClass.PRIVATE_KEY}):
                                    priv = j
                                    break
                            except pkcs11.exceptions.MultipleObjectsReturned:
                                for j in session.get_objects({Attribute.CLASS: ObjectClass.PRIVATE_KEY}):
                                    priv = j
                                    break

                            certificate = next(session.get_objects({Attribute.CLASS: pkcs11.constants.ObjectClass.CERTIFICATE}))
                            der_bytes = certificate[Attribute.VALUE]
                            pem_bytes = pem.armor('CERTIFICATE', der_bytes)
                            token_certificate = pem_bytes.decode()

                            try:
                                # pub = session.get_key(object_class=pkcs11.constants.ObjectClass.PUBLIC_KEY, label=TOKEN_LABEL)
                                pub = encode_rsa_public_key(session.get_key(object_class=pkcs11.constants.ObjectClass.PUBLIC_KEY))

                            except pkcs11.MultipleObjectsReturned:
                                for i in session.get_objects({Attribute.CLASS: pkcs11.constants.ObjectClass.PUBLIC_KEY}):
                                    pub = encode_rsa_public_key(i)
                                    break

                            except pkcs11.exceptions.NoSuchKey:
                                cert2 = x509.load_pem_x509_certificate(pem.armor('CERTIFICATE', der_bytes),default_backend())
                                # pubdata = cert2.public_key().public_bytes(cryptography.hazmat.primitives.serialization.Encoding.DER,cryptography.hazmat.primitives.serialization.PublicFormat.SubjectPublicKeyInfo)
                                pubdata = cert2.public_key().public_bytes(cryptography.hazmat.primitives.serialization.Encoding.DER,cryptography.hazmat.primitives.serialization.PublicFormat.SubjectPublicKeyInfo)
                                # pub = pem.armor('RSA PUBLIC KEY', pubdata)
                                pub = pubdata

                            NASC_CPF_MATRICULA_RG_SIGLAEXPEDIDOR_UF = NASCIMENTO + CPF + MATRICULA + RG + SIGLAEXPEDIDOR_E_UF
                            INSTENSINO_GRAUESCOLARIDADE_NOMECURSO_MUNICINSTIT_UF = str(INSTENSINO) + str(ESCOLARIDADE) + str(NOME_CURSO) + str(MUNICIPIO_INSTENSINO) + str(UF_INSTENSINO)

                            extension1 = Extension({'extn_id': ExtensionId('2.16.76.1.10.1'),
                                                    'critical': False,
                                                    'extn_value': NASC_CPF_MATRICULA_RG_SIGLAEXPEDIDOR_UF.encode()
                                                    })
                            extension2 = Extension({'extn_id': ExtensionId('2.16.76.1.10.2'),
                                                    'critical': False,
                                                    'extn_value': unidecode.unidecode(
                                                        INSTENSINO_GRAUESCOLARIDADE_NOMECURSO_MUNICINSTIT_UF).encode()
                                                    })

                            extension3 = False

                            if NOME_SOCIAL is not False or NOME_SOCIAL != "False":
                                extension3 = Extension({'extn_id': ExtensionId('2.16.76.1.4.3'),
                                                        'critical': False,
                                                        'extn_value': unidecode.unidecode(
                                                            NOME_SOCIAL).encode()
                                                        })


                            authority_key_identifier = Extension({
                                'extn_id': ExtensionId('authority_key_identifier'),
                                'critical': False,
                                'extn_value': AuthorityKeyIdentifier({
                                  'key_identifier': AUTHORITY_KEY_IDENTIFIER.encode()
                                    })
                            })

                            authority_information_access = Extension({
                                'extn_id': ExtensionId('authority_information_access'),
                                'critical': False,
                                'extn_value': [{
                                    'access_method': AccessMethod('1.3.6.1.5.5.7.48.5'),
                                    'access_location': GeneralName('uniform_resource_identifier', URI(AUTHORITY_INFORMATION_ACCESS))
                                }]
                            })
                            crl_distribution_point = Extension({
                                'extn_id': ExtensionId('crl_distribution_points'),
                                'critical': False,
                                'extn_value': [{
                                    'distribution_point': DistributionPointName('full_name', [GeneralName('uniform_resource_identifier', URI(CRL_DISTRIBUTION_POINT))]),
                                    # 'crl_issuer': [GeneralName('uniform_resource_identifier', URI(CRL_DISTRIBUTION_POINT))]
                                }]
                            })

                            # sha256_rsa
                            signed_digest_algo = 'sha256_rsa'


                            if extension3:
                                extensions_tuple = (extension1, extension2, extension3, authority_information_access, crl_distribution_point, authority_key_identifier)
                            else:
                                extensions_tuple = (extension1, extension2, authority_information_access, crl_distribution_point, authority_key_identifier)


                            tbs = TbsCertificate({
                                'version': Version(1),
                                'serial_number': int(SERIAL),
                                'issuer': Name.build({
                                    'common_name': EEA_COMMON_NAME,
                                }),
                                'subject': Name.build({
                                    'common_name': COMMON_NAME,
                                }),
                                'signature': {
                                    'algorithm': signed_digest_algo,
                                    'parameters': None,
                                },
                                'extensions': (extensions_tuple),

                                'validity': {
                                    'not_before': Time({
                                        'general_time': GeneralizedTime(parser.parse(NOT_VALID_BEFORE)),
                                    }),
                                    'not_after': Time({
                                        'general_time': GeneralizedTime(parser.parse(NOT_VALID_AFTER)),
                                    }),
                                },
                                'subject_public_key_info': {
                                    'algorithm': {
                                        'algorithm': 'rsa',
                                        'parameters': None,
                                    },
                                    # 'public_key': RSAPublicKey.load(encode_rsa_public_key(pub)),
                                    'public_key': RSAPublicKey.load(pub),
                                }
                            })

                            # Sign the TBS Certificate
                            value = priv.sign(tbs.dump(),
                                              mechanism=Mechanism.SHA256_RSA_PKCS)

                            cert = Certificate({
                                'tbs_certificate': tbs,
                                'signature_algorithm': {
                                    'algorithm': signed_digest_algo,
                                    'parameters': None,
                                },
                                'signature_value': value,
                            })
                            attribute_certificate = pem.armor('CERTIFICATE', cert.dump()).decode()
                            return (attribute_certificate + token_certificate).strip()
                    else:
                        return 'Token not found'
            except TokenNotPresent:
                pass
```

**Comment by joernheissler** [comment]
@ftbarata 
Before I take a closer look, would you please attach your generated `cert.pem` and complete the code so I can run it on my machine?

**Comment by joernheissler** [comment]
Thanks for the cert.
Did you use the latest version of asn1crypto, i.e. git master? There are some `NULL` related differences between what's in your cert and what openssl produces.
The version number should be 2, not 1. See rfc5280:

```
     extensions      [3]  Extensions OPTIONAL
                          -- If present, version MUST be v3 --  }
```

Still not the real issue.

I had a look at the pubkeys inside a new cert and your cert, with `dumpasn1`.
New cert (from openssl):
```
  0 522: SEQUENCE {
  4 513: . INTEGER
       : . . 00 B1 FE C4 2B FF 4F 86 DA A1 10 5D 98 BB DA 2C
       : . . 21 89 9C 9D 72 00 88 65 66 E9 09 65 3E AA F0 8D
       : . . 1E F5 DF 9B 99 BB BA 68 88 48 9B 62 2F D8 BB 2D
       : . . F3 70 A5 BB 1D DA FD 94 57 69 9E 1B 7D C1 9C EA
       : . . F7 4D 1D B2 84 97 55 6A 33 64 9A 80 94 03 21 F6
       : . . 2D CA 02 71 0D 45 9A C9 2D 01 1A 4B 45 C5 22 27
       : . . 9D 2F 51 BB 0D 94 8F F0 63 64 16 DF F0 53 90 18
       : . . 49 79 48 8D 86 41 9B E4 93 04 1B A6 71 D0 C4 F7
       : . . FC 71 4D 11 B4 2A 7F FE 78 43 A7 96 E7 8F 1C 3F
       : . . C6 29 89 97 14 B9 B9 44 F5 4D F9 3A 7C D9 6F E3
       : . . C7 81 27 30 26 75 A3 AE 1A 95 DA 41 51 54 34 62
       : . . D6 53 C7 81 A3 66 9F A9 A5 F7 F5 37 ED 46 6F 1B
       : . . FB AB 52 82 4D 53 B2 EC D0 03 FA 33 CA 20 5D 2E
       : . . CE 96 0D EB 0B 3B 45 66 11 AF C8 B1 DE AA 51 B6
       : . . 36 F5 88 79 00 91 DD 08 5D 25 D3 50 42 DB B4 08
       : . . C2 29 4E A9 72 93 87 F3 AD FC 0A 58 1C 11 D1 E4
       : . . 58 A6 16 AE 99 B2 3E 4B 67 DB BF 7C 39 E3 62 DA
       : . . 4C 08 57 BE CD 73 08 0C F5 F0 37 63 47 5B AA DF
       : . . 6F 32 FF 0F 0D AA F9 B5 C0 27 F8 56 17 B4 BB 15
       : . . 8E A3 21 6F 58 C0 0D 4B FE 11 FB 4C 69 FB D7 2E
       : . . F1 34 D9 48 CB 2F 03 E0 DB 6D 06 67 02 7B C8 76
       : . . 1C 55 88 0F 85 0A 68 98 FA AE A3 AB 24 99 A0 B4
       : . . 2F 82 BB 9D 6B 83 BB 77 63 FA CA CC 16 DB 6C 1A
       : . . 72 38 F8 F9 04 B2 AC 17 37 12 E7 32 5C 81 C2 8F
       : . . E6 D2 9F 9B 7C E5 44 F2 6C C0 68 8C FC 14 21 F9
       : . . F7 7D D7 41 DD 9D 10 FB 59 3F 70 B0 43 FA 77 95
       : . . A3 BD C5 6E 34 B0 FB 13 D0 75 96 4E E5 3B 2F 75
       : . . 98 66 92 17 7F E6 B9 A7 2D D0 18 95 07 25 18 91
       : . . 36 8E 14 9C C3 75 42 8D E9 D0 AE 4E 88 14 A4 3F
       : . . E5 38 35 9A 7F D6 D7 01 EA BD 47 DB 81 1C 7A B8
       : . . 02 B8 31 23 15 F5 1F 14 C8 70 9A 68 E2 CD 50 E9
       : . . 5F A5 1F A4 23 3B 38 90 BD 62 E6 B8 63 44 0A 1F
       : . . CB
521   3: . INTEGER 65537
       : . }
```

Your cert:
```
  0 546: SEQUENCE {
  4  13: . SEQUENCE {
  6   9: . . OBJECT IDENTIFIER rsaEncryption (1 2 840 113549 1 1 1)
 17   0: . . NULL
       : . . }
 19 527: . BIT STRING
       : . . 30 82 02 0A 02 82 02 01 00 9D 60 77 AA 0F CA F0
       : . . 2F 60 2D 01 E5 F5 08 B5 71 54 FD CB 17 DB 23 44
       : . . 39 52 63 AF F4 9E B9 2B F9 6C 4D 20 21 CF E4 52
       : . . 3A 18 54 D3 2E 51 EF 82 4C 16 3F 82 4A 08 8B 04
       : . . 7B AA BE C3 B2 9F 63 9F C1 53 2E 70 0B AE 7E A3
       : . . D6 C6 DB 92 80 F8 CA D4 C8 DD 61 D4 BA 27 9F CF
       : . . FA 00 A6 FF 87 E7 33 EC C2 3D C9 A9 4C 97 68 AE
       : . . DB CC DE 40 91 CD CF 34 55 33 45 BD FE 51 BB 58
       : . . 03 67 D7 8A 70 40 7B 0C 6B A5 98 9D 19 7D 00 FA
       : . . 2A 02 FB EA 8F AB 4E 80 3D 38 A8 F5 25 92 04 11
       : . . 84 66 09 8B 38 01 E9 91 D1 E1 35 40 1A 3F D3 09
       : . . 5D 17 10 F6 4E 24 8A 53 AD DE E7 B0 44 FE C4 28
       : . . CC 8C 18 3C 8D 3D EA 83 B5 60 96 08 48 9F EE F6
       : . . 62 2D 27 2B 29 26 37 97 6E 67 09 6F 70 54 DF 2A
       : . . 43 41 BC 98 9C 0C 4C 58 67 B5 97 C6 EF 4F 7C 91
       : . . 13 74 7C 85 40 B2 DC 93 E0 AB 32 54 83 96 82 3F
       : . . 2B DA 96 7D D7 7C 89 7E 86 CC 44 EC A5 F3 D5 F9
       : . . 95 E4 76 F7 C8 33 C0 38 4D D9 42 89 5C 79 9F ED
       : . . 71 73 A8 E4 E0 D0 79 78 74 AE 4B CD 28 34 ED 1C
       : . . B6 0E AA 28 17 07 6F C6 30 57 95 67 40 56 44 DD
       : . . 66 8E 65 33 91 50 1A BE 6E 34 31 72 2F 60 D0 C0
       : . . 3B 66 A4 CA D0 ED 0A D5 03 8B 1A 5D FC 01 B0 C5
       : . . 8C 7A 5D B4 B2 25 FC B7 66 CE 14 85 C7 73 51 E2
       : . . 50 3C 44 4E 00 90 C3 8E 78 DA 9C 0E B4 53 E3 F3
       : . . E5 05 6A 0F B2 A5 98 72 93 CB E8 01 A5 D0 8F 0D
       : . . EA 1A E6 D6 23 AF 23 14 D6 53 AC D5 E3 41 38 48
       : . . 94 95 88 F3 73 96 8D CB E6 22 BE 12 3E 06 DF F6
       : . . 12 08 1F 3C E7 49 DC EA 3D 75 DD 01 94 4D 4B D7
       : . . F1 AF 19 A0 A1 37 06 E0 8E DC BB 58 59 80 1B FD
       : . . 1C 72 1A 50 AA F6 33 05 C0 74 D8 AA A1 EE F5 C0
       : . . 39 0B 08 A5 31 F3 F7 D5 26 78 6C C2 A1 C1 1D 80
       : . . 23 F8 A8 C1 C3 2A 09 5B 52 65 88 BF 75 40 E4 F7
       : . . 06 3C F6 7A 98 FB 92 3E ED 02 03 01 00 01
       : . }
```


The algorithm is already specified outside the embedded structure. The contents must be `RSAPublicKey`, not `PublicKeyInfo`.

Now back to your code:
`'public_key': RSAPublicKey.load(pub),`

I assume `pub` contains such a `PublicKeyInfo`, not `RSAPublicKey`.
Try: `'subject_public_key_info': PublicKeyInfo.load(pub)`

**Comment by ftbarata** [comment]
Hi again @joernheissler !
If you are in doubt about what **pub** is,
```
pub = encode_rsa_public_key(session.get_key(object_class=pkcs11.constants.ObjectClass.PUBLIC_KEY))
```
So, pub is the Public Key extracted from the USB token, right?

And, considering your suggestion, I am in doubt if you mean to do:
```
 },
                                'subject_public_key_info': {
                                    'algorithm': {
                                        'algorithm': 'rsa',
                                        'parameters': None,
                                    },
                                     'public_key': PublicKeyInfo.load(pub),
                                }
```
Or 
```
 },
                               'subject_public_key_info': PublicKeyInfo.load(pub)
                                }
```
In both cases, the variable PublicKeyInfo does not exist. Besides, the second example I gave may be incorrect for asn1crypto syntax stuff. Do you known the asn1crypto properly usage?

**Comment by joernheissler** [comment]
The latter.
`from asn1crypto.keys import PublicKeyInfo`.

Your syntax should be fine. Maybe you can remove all pkcs11 stuff from your code and mock up some values, e.g. include your `pub` variable in base64 or hex form.

**Comment by ftbarata** [comment]
Hi, I did what you told.
Here is the new certificate. Could you take a look if now it's correct?
I tried to load it at https://redkestrel.co.uk/products/decoder/ but it does not show the public key too. I'm not sure if I am trying to check this at the right place.

[certificado_new.zip](https://github.com/wbond/asn1crypto/files/2792891/certificado_new.zip)

**Comment by ftbarata** [comment]
@joernheissler,
Let me add one more question. I'm trying to generate certificate most similar possible to this attached certificate. This attached certificate is made by a concurrent.
I wonder, how they've merged the attribute certificate and the certificate which was used to sign, into a unique certificate? In my pem file, I have two blocks of begin-end certificate. But, openssl and other online pem decoder websites reads just the first block. Why does it happens?
What is your analysis about this crt file?

[concurrent.zip](https://github.com/wbond/asn1crypto/files/2792913/concurrent.zip)

**Comment by joernheissler** [comment]
No, certificado_new.zip isn't correct either.
Now it doesn't have any `PublicKeyInfo` struct at all.

Please modify your code so I can actually run it.

> I wonder, how they've merged the attribute certificate and the certificate which was used to sign, into a unique certificate?

By "merge .. into a unique certificate" you mean two PEM blocks in one file? It's just as simple as that. Two PEM blocks in one file. Open a file, write two PEM blocks :)

> openssl and other online pem decoder websites reads just the first block

Yep, those tools only read the first PEM. You can split this into two files and decode them separetely.
asn1crypto's unarmor function can read both if used as a generator.

I'm a bit confused now. Your PEMs contain two certs. I don't see how they are related to that Attribute Certificate.

**Comment by ftbarata** [comment]
Hello. Well, I've attached the full code of the function. I am not expert in cryptography, so it would be too difficult for me to adapt the code to swtich from the USB Token to self signed certificate created with openssl. I hope you can adapt the code to do this. 
The function signature parameters are all strings. 

My PEM contains two certs. Right. The first block is the attribute certificate created for specific purposes. The second block is the certificate extracted from USB Token extracted via #PKCS11 API. I am building a single PEM with two certificates to be able to prove that the attribute certificate was signed by that USB Token, and not by anyone else, because, as far as I know, the signature of the attribute certificate (first block) contains the public key of the USB Token certificate(second block), and the trust chain is built upon this chain. Is it correct?

[code.zip](https://github.com/wbond/asn1crypto/files/2793152/code.zip)

**Comment by joernheissler** [comment]
> it would be too difficult for me to adapt the code to swtich from the USB Token to self signed certificate created with openssl.

Misunderstanding. The token/pkcs#11 stuff should be removed, yes. But what I was hoping for was something like:

```python3
#!/usr/bin/env python3
from asn1crypto.x509 import TbsCertificate

pub = # Some constant value, the one that you actually get.
tbs = TbsCertificate( # copy+paste from your code.
)
print(tbs.dump().hex())
```

The above code needs to run on my machine. No dependencies on openssl or your usb token. And the `tbs` must be what you get in your real code.

This is only to address your original issue (problem with nested asn.1 structures). Also I don't see how your original issue is related to Attribute Certs. What you create with `TbsCertificate` is a regular public key cert.

**Comment by joernheissler** [comment]
Unless you provide a proper test case, I won't be able to help you. Sorry.
See http://sscce.org/ for more information.

**Comment by ftbarata** [comment]
Hi @joernheissler , I understand you, no problem. I want  to thank you a lot for helping me. I'm working hard to try to make a working code.
The code below is almost running, except for the line:
``` 
'public_key': RSAPublicKey.load(pubkey),
```
Which produces:
```
Traceback (most recent call last):
  File "agent_test.py", line 217, in <module>
    createCertificateOsCrypto()
  File "agent_test.py", line 197, in createCertificateOsCrypto
    'public_key': RSAPublicKey.load(pubkey),
  File "/home/fellipe/python_virtualenvs/gerador_certificado/lib/python3.6/site-packages/asn1crypto/core.py", line 223, in load
    raise TypeError('encoded_data must be a byte string, not %s' % type_name(encoded_data))
TypeError: encoded_data must be a byte string, not str

```
The idea is to change the keys and certificate used from USB token to self signed generated key pairs, so the pkcs11 stuff will not be used. Even you or I can fix this little error, I guess the code could complain about the fact that the pubkey (which I pasted in PEM format, from the token) does not match the privkey(auto generated). In this case, the only way I think can be used is to use self signed certificate, pub and priv key. Right?

```
from oscrypto import asymmetric
import datetime
from dateutil import parser
from asn1crypto import pem
from asn1crypto.x509 import Certificate, TbsCertificate, Time, Name, Extension, ExtensionId,Version, AccessMethod, GeneralName, URI, DistributionPointName, AuthorityKeyIdentifier
from asn1crypto.keys import RSAPublicKey
import unidecode
from pkcs11 import Mechanism
from asn1crypto.core import GeneralizedTime


def createCertificateOsCrypto():

    SERIAL='1234'
    COMMON_NAME='JOAO TESTE'
    NOME_SOCIAL='JOAO TESTE SOCIAL'
    NASCIMENTO='10111987'
    CPF='92833746128'
    MATRICULA='10293183'
    RG='2948183481'
    SIGLAEXPEDIDOR_E_UF='BLWRWK'
    INSTENSINO='CNDIEO'
    UF_INSTENSINO='AO'
    ESCOLARIDADE='SUPERIOR'
    NOME_CURSO='DIRTO'
    MUNICIPIO_INSTENSINO='Casacaiada'
    EEA_COMMON_NAME='AMEB'
    NOT_VALID_BEFORE=str(datetime.datetime.now())
    NOT_VALID_AFTER=str(datetime.datetime(datetime.datetime.now().year + 1, 3, 31, hour=23, minute=59,second=59))
    AUTHORITY_KEY_IDENTIFIER='9bd334399eea4c152d3a73597af7c38a4d81c75b89bbafee6ca48d55a0ac58ee6642ff13ed0275b145c1a7d913116bf879914e5403e77d0e96a5761fa70accee'
    AUTHORITY_INFORMATION_ACCESS='http://test.com/aia'
    CRL_DISTRIBUTION_POINT='http://test.com/crl'

    token_certificate = '''
        -----BEGIN CERTIFICATE-----
    MIIGYDCCBEigAwIBAgIBBDANBgkqhkiG9w0BAQ0FADCBlzELMAkGA1UEBhMCQlIx
    EzARBgNVBAoMCklDUC1CcmFzaWwxPTA7BgNVBAsMNEluc3RpdHV0byBOYWNpb25h
    bCBkZSBUZWNub2xvZ2lhIGRhIEluZm9ybWFjYW8gLSBJVEkxNDAyBgNVBAMMK0F1
    dG9yaWRhZGUgQ2VydGlmaWNhZG9yYSBSYWl6IEJyYXNpbGVpcmEgdjUwHhcNMTYw
    NzIwMTMzMjA0WhcNMjkwMzAyMTIwMDA0WjCBkDELMAkGA1UEBhMCQlIxEzARBgNV
    BAoMCklDUC1CcmFzaWwxNDAyBgNVBAsMK0F1dG9yaWRhZGUgQ2VydGlmaWNhZG9y
    YSBSYWl6IEJyYXNpbGVpcmEgdjUxNjA0BgNVBAMMLUFDIFNlY3JldGFyaWEgZGEg
    UmVjZWl0YSBGZWRlcmFsIGRvIEJyYXNpbCB2NDCCAiIwDQYJKoZIhvcNAQEBBQAD
    ggIPADCCAgoCggIBAJ1gd6oPyvAvYC0B5fUItXFU/csX2yNEOVJjr/SeuSv5bE0g
    Ic/kUjoYVNMuUe+CTBY/gkoIiwR7qr7Dsp9jn8FTLnALrn6j1sbbkoD4ytTI3WHU
    uiefz/oApv+H5zPswj3JqUyXaK7bzN5Akc3PNFUzRb3+UbtYA2fXinBAewxrpZid
    GX0A+ioC++qPq06APTio9SWSBBGEZgmLOAHpkdHhNUAaP9MJXRcQ9k4kilOt3uew
    RP7EKMyMGDyNPeqDtWCWCEif7vZiLScrKSY3l25nCW9wVN8qQ0G8mJwMTFhntZfG
    7098kRN0fIVAstyT4KsyVIOWgj8r2pZ913yJfobMROyl89X5leR298gzwDhN2UKJ
    XHmf7XFzqOTg0Hl4dK5LzSg07Ry2DqooFwdvxjBXlWdAVkTdZo5lM5FQGr5uNDFy
    L2DQwDtmpMrQ7QrVA4saXfwBsMWMel20siX8t2bOFIXHc1HiUDxETgCQw4542pwO
    tFPj8+UFag+ypZhyk8voAaXQjw3qGubWI68jFNZTrNXjQThIlJWI83OWjcvmIr4S
    Pgbf9hIIHzznSdzqPXXdAZRNS9fxrxmgoTcG4I7cu1hZgBv9HHIaUKr2MwXAdNiq
    oe71wDkLCKUx8/fVJnhswqHBHYAj+KjBwyoJW1JliL91QOT3Bjz2epj7kj7tAgMB
    AAGjgbswgbgwHQYDVR0OBBYEFBqY5kPKHN2SnpljRVoq6R+HIM01MA8GA1UdEwEB
    /wQFMAMBAf8wDgYDVR0PAQH/BAQDAgEGMBQGA1UdIAQNMAswCQYFYEwBAQgwADA/
    BgNVHR8EODA2MDSgMqAwhi5odHRwOi8vYWNyYWl6LmljcGJyYXNpbC5nb3YuYnIv
    TENSYWNyYWl6djUuY3JsMB8GA1UdIwQYMBaAFGmovnXZxO9s5xNF5GFu5Wj4tkBe
    MA0GCSqGSIb3DQEBDQUAA4ICAQBrQuAL6TWbdnOpHbgSzAd9Pkc+vr5uTd7ml4xf
    PPs/I+BNCGT9Q6OTx/26m6q9rOrl6/9AASYDE5esiwBlaQ4OPzQQ37zrf5d4FnGx
    nsRMdjEL2pjks7ull66LZX8k5HOfnxy5iYo1hTy46UYg28PXdL55qTljilj4LueN
    FlTCmK2m9Vo1E6F/Ss79D31uwVBadgoK/i95dFONNlSj/w3/sa9Pbkq3JCJ10ET0
    1GmBSTrtired+zzcj26QT0hjQQ5PUB6wV2+bhUx+WN/rXiLph/DPvy7gg8hrn4mV
    HBYOEPPoq7qBsX77cswycENKXrlq+gHA2Lj8hkrbfQt4pZQzT+6nLOSOyqMI21ql
    781eErJySwJ0R9LdPQNm3MUS/ifoRPdjFGWUktBRue/03QrVYtwFBMaIjF/p93Bm
    b/42xfkL/TG/W6EicBcGLms2SU4pBtw+NDFMQ1YXxNJQoNJ2uzxnzBSqdr5bF5qZ
    th4EHob+I8uUFYylIoCHWvMD1pAxTu8fC9366lkt7cpBARiOdB2MN31JQK3nxjeQ
    eXHiudm8twSzNp0wbJViUiRfNZbqH3yNe8ZTYUQds7hCCcZh3pZbe4PNWS2WDiif
    F9uXRdfAL3qsEubQOrA/s+EvZha6afCs4d4BlGKQsf64r0iPnX6hFxR4h4sXRI9x
    5xRMtA==
    -----END CERTIFICATE-----
        '''


    public_key_not_used, priv = asymmetric.generate_pair('rsa', bit_size=2048)

    pubkey = '''
        -----BEGIN RSA PUBLIC KEY-----
        MIIBCgKCAQEAieDitqs5DaDOXuk3gm228BMGaqNSEWxRHoKNTxwMG+0h5JTc4fiX
        dM1XLKDIdovGQuA17hniBPQydSsl9zZse5DAkSFlJV2e+86zuxUb1hI0UOe/E8FM
        Ra2ynlhZ7cM5eAwslvegNh25ZC4EJftevbCpgVJVVrO0wkLwKH6RRPmB2GNyaJW/
        O3E4pqqu5QR7MFrztTNbiDx0NeRrhZ81VMDhAPxZX5Fes2zIcCmOP6XFaDCZT6lq
        CdIootegwxqMDzDVczE5UiGSTp4gKcy/sDr5HfU3mqhZMNsZ+v4dvGr7WGt4kAKs
        ygZsK7OkKsVUSICO4VvhDjnp4IxIbTKvkQIDAQAB
        -----END RSA PUBLIC KEY-----
    
    '''

    NASC_CPF_MATRICULA_RG_SIGLAEXPEDIDOR_UF = NASCIMENTO + CPF + MATRICULA + RG + SIGLAEXPEDIDOR_E_UF
    INSTENSINO_GRAUESCOLARIDADE_NOMECURSO_MUNICINSTIT_UF = str(INSTENSINO) + str(ESCOLARIDADE) + str(
        NOME_CURSO) + str(MUNICIPIO_INSTENSINO) + str(UF_INSTENSINO)

    extension1 = Extension({'extn_id': ExtensionId('2.16.76.1.10.1'),
                            'critical': False,
                            'extn_value': NASC_CPF_MATRICULA_RG_SIGLAEXPEDIDOR_UF.encode()
                            })
    extension2 = Extension({'extn_id': ExtensionId('2.16.76.1.10.2'),
                            'critical': False,
                            'extn_value': unidecode.unidecode(
                                INSTENSINO_GRAUESCOLARIDADE_NOMECURSO_MUNICINSTIT_UF).encode()
                            })

    extension3 = False

    if NOME_SOCIAL is not False or NOME_SOCIAL != "False":
        extension3 = Extension({'extn_id': ExtensionId('2.16.76.1.4.3'),
                                'critical': False,
                                'extn_value': unidecode.unidecode(
                                    NOME_SOCIAL).encode()
                                })

    authority_key_identifier = Extension({
        'extn_id': ExtensionId('authority_key_identifier'),
        'critical': False,
        'extn_value': AuthorityKeyIdentifier({
            'key_identifier': AUTHORITY_KEY_IDENTIFIER.encode()
        })
    })

    authority_information_access = Extension({
        'extn_id': ExtensionId('authority_information_access'),
        'critical': False,
        'extn_value': [{
            'access_method': AccessMethod('1.3.6.1.5.5.7.48.5'),
            'access_location': GeneralName('uniform_resource_identifier',
                                           URI(AUTHORITY_INFORMATION_ACCESS))
        }]
    })
    crl_distribution_point = Extension({
        'extn_id': ExtensionId('crl_distribution_points'),
        'critical': False,
        'extn_value': [{
            'distribution_point': DistributionPointName('full_name', [
                GeneralName('uniform_resource_identifier', URI(CRL_DISTRIBUTION_POINT))]),
            # 'crl_issuer': [GeneralName('uniform_resource_identifier', URI(CRL_DISTRIBUTION_POINT))]
        }]
    })

    # sha256_rsa
    signed_digest_algo = 'sha256_rsa'

    if extension3:
        extensions_tuple = (
        extension1, extension2, extension3, authority_information_access, crl_distribution_point,
        authority_key_identifier)
    else:
        extensions_tuple = (
        extension1, extension2, authority_information_access, crl_distribution_point,
        authority_key_identifier)

    tbs = TbsCertificate({
        'version': Version(1),
        'serial_number': int(SERIAL),
        'issuer': Name.build({
            'common_name': EEA_COMMON_NAME,
        }),
        'subject': Name.build({
            'common_name': COMMON_NAME,
        }),
        'signature': {
            'algorithm': signed_digest_algo,
            'parameters': None,
        },
        'extensions': (extensions_tuple),

        'validity': {
            'not_before': Time({
                'general_time': GeneralizedTime(parser.parse(NOT_VALID_BEFORE)),
            }),
            'not_after': Time({
                'general_time': GeneralizedTime(parser.parse(NOT_VALID_AFTER)),
            }),
        },
        'subject_public_key_info': {
            'algorithm': {
                'algorithm': 'rsa',
                'parameters': None,
            },
            # 'public_key': RSAPublicKey.load(encode_rsa_public_key(pub)),
                'public_key': RSAPublicKey.load(pubkey),
        }
        # 'subject_public_key_info': PublicKeyInfo.load(pub)
    })

    # Sign the TBS Certificate
    value = priv.sign(tbs.dump(),
                      mechanism=Mechanism.SHA256_RSA_PKCS)

    cert = Certificate({
        'tbs_certificate': tbs,
        'signature_algorithm': {
            'algorithm': signed_digest_algo,
            'parameters': None,
        },
        'signature_value': value,
    })
    attribute_certificate = pem.armor('CERTIFICATE', cert.dump()).decode()
    print(attribute_certificate + token_certificate).strip()

createCertificateOsCrypto()
```

**Comment by ftbarata** [comment]
Sorry, I made I mistake. I was passing public key instead of public key info.

**Comment by 4devs-net-br** [comment]
https://4devs.net.br/gerador-cpf
