### ISSUE TITLE
cms.AttributeCertificateInfoV2  KeyError: None

### ISSUE THREAD

**Issue by ftbarata** [wbond/asn1crypto#132]
Hi @joernheissler and everyone,
I'm stuck on the 'attributes' key of AttributeCertificateInfoV2. I tried many ways, no success:

```
attribute_certificate_infov2 = cms.AttributeCertificateInfoV2({
                                'version': 1,
                                'serial_number': int(SERIAL),
                                'issuer': cms.AttCertIssuer({
                                    'v1_form':  [GeneralName('directory_name', Name.build({'common_name': EEA_COMMON_NAME})),
                                                 GeneralName('directory_name', Name.build({'organization_name':'Some organization name'})),
                                                 GeneralName('directory_name', Name.build({'organizational_unit_name':'Some CA Name'}))
                                     ]})
                                ,
                                'holder': {
                                        'entity_name': [GeneralName('directory_name',Name.build({'common_name': COMMON_NAME})),
                                                        GeneralName('directory_name',Name.build({'country_name':'BR'})),
                                                        GeneralName('directory_name',Name.build({'organization_name': 'Some organization name'})),
                                                        GeneralName('directory_name',Name.build({'organizational_unit_name':'Some Name'}))
                                                        ]
                                    },
                                'attributes': [cms.AttCertAttribute(cms.AttCertAttributeType('authentication_info'), cms.SvceAuthInfo({'service':Name.build({'common_name':'Test'}), 'ident':Name.build({'common_name':'Test2'})}))],

                                'signature': {
                                    'algorithm': signed_digest_algo,
                                    'parameters': None,
                                },
                                'extensions': (extensions_tuple),

                                'att_cert_validity_period': cms.AttCertValidityPeriod({
                                    'not_before_time': GeneralizedTime(parser.parse(NOT_VALID_BEFORE)),
                                    'not_after_time': GeneralizedTime(parser.parse(NOT_VALID_AFTER))
                                })
                            })

```
```
File "agent.py", line 149, in createCertificateOsCrypto
    'attributes': [cms.AttCertAttribute(cms.AttCertAttributeType('authentication_info'), cms.SvceAuthInfo({'service':Name.build({'common_name':'Teste'}), 'ident':Name.build({'common_name':'Test2'})}))],
  File "/root/sigcerta/.virtualenv/lib/python3.5/site-packages/asn1crypto/core.py", line 3154, in __init__
    self.__setitem__(key, value[key])
  File "/root/sigcerta/.virtualenv/lib/python3.5/site-packages/asn1crypto/core.py", line 3310, in __setitem__
    new_value = self._make_value(field_name, field_spec, value_spec, field_params, value)
  File "/root/sigcerta/.virtualenv/lib/python3.5/site-packages/asn1crypto/core.py", line 3541, in _make_value
    wrapper.validate(value.class_, value.tag, value.contents)
  File "/root/sigcerta/.virtualenv/lib/python3.5/site-packages/asn1crypto/core.py", line 1224, in validate
    asn1 = self._format_class_tag(class_, tag)
  File "/root/sigcerta/.virtualenv/lib/python3.5/site-packages/asn1crypto/core.py", line 1243, in _format_class_tag
    return '[%s %s]' % (CLASS_NUM_TO_NAME_MAP[class_].upper(), tag)
KeyError: None
```
What's wrong? This error is not so helpfull

If  I try to use AttributeCertificateInfoV1:
```
attribute_certificate_infov1 = cms.AttributeCertificateInfoV1({
                            'subject': cms.AttCertSubject('subject_name', [GeneralName('directory_name', Name.build({'common_name': COMMON_NAME}))]),
                            'issuer': [GeneralName('directory_name', Name.build({'common_name': EEA_COMMON_NAME}))],
                            'signature': {
                                'algorithm': signed_digest_algo,
                                'parameters': None,
                            },
                            'serial_number': int(SERIAL),
                            'att_cert_validity_period': cms.AttCertValidityPeriod({
                                'not_before_time': GeneralizedTime(parser.parse(NOT_VALID_BEFORE)),
                                'not_after_time': GeneralizedTime(parser.parse(NOT_VALID_AFTER))
                            }),
                            'extensions': (extensions_tuple),
                            'attributes': [Attribute(ObjectIdentifier('2.5.4.3'), {'common_name': 'test'})]

                            })
```
I get:

```
File "agent.py", line 177, in createCertificateOsCrypto
    'attributes': [Attribute( ObjectIdentifier('2.5.4.3'), {'common_name': 'test'})]
  File "/root/sigcerta/.virtualenv/lib/python3.5/site-packages/aenum/__init__.py", line 1961, in __call__
    return cls._create_(value, names, module=module, type=type, start=start)
  File "/root/sigcerta/.virtualenv/lib/python3.5/site-packages/aenum/__init__.py", line 2087, in _create_
    _, first_enum = cls._get_mixins_(bases)
  File "/root/sigcerta/.virtualenv/lib/python3.5/site-packages/aenum/__init__.py", line 2152, in _get_mixins_
    raise TypeError("cannot extend enumerations via subclassing.")
TypeError: cannot extend enumerations via subclassing.
```
I don't really know how to set the sequence of Attribute object, I tried some ways, no success too.

**Comment by wbond** [comment]
## First Error

If you look at the stack trace, the issue starts with your code:

```python
'attributes': [cms.AttCertAttribute(cms.AttCertAttributeType('authentication_info'), cms.SvceAuthInfo({'service':Name.build({'common_name':'Teste'}), 'ident':Name.build({'common_name':'Test2'})}))],
```

If you look at the `AttCertAttribute` class in `cms.py`, you'll see it extends `Sequence`. Looking at `core.Sequence`, the `__init__` function has a situation of:

```python
def __init__(self, value=None, default=None, **kwargs)
```

So you are passing `cms.AttCertAttributeType('authentication_info')` to `value` and `cms.SvceAuthInfo({'service':Name.build({'common_name':'Teste'}), 'ident':Name.build({'common_name':'Test2'})})` to `default`, which isn't correct.

To initialize a `Sequence`, you pass in a `dict` of the fields. There was also an issue where you were passing a `Name` where a `GeneralName` was expected. However, there is also a bug you uncovered. If you try to construct a `Choice` type that contains a `Choice` type and assign it to a field of a `Sequence`, it will fail saying there isn't a value provided.

Here is the correct code to build the `AttCertAttributeType` that you want:

```python
from asn1crypto import cms
from asn1crypto.x509 import Name, GeneralName

cms.AttCertAttribute({
    'type': cms.AttCertAttributeType('authentication_info'),
    'values': [cms.SvceAuthInfo({
        'service': GeneralName('directory_name', Name.build({'common_name':'Test'})),
        'ident': GeneralName('directory_name', Name.build({'common_name':'Test2'}))
    })]
})
```

Here is the error you will get when you run it:

```
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    'ident': GeneralName('directory_name', Name.build({'common_name':'Test2'}))
  File "/Users/wbond/dev/git/asn1crypto/asn1crypto/core.py", line 3170, in __init__
    raise e
  File "/Users/wbond/dev/git/asn1crypto/asn1crypto/core.py", line 3154, in __init__
    self.__setitem__(key, value[key])
  File "/Users/wbond/dev/git/asn1crypto/asn1crypto/core.py", line 3326, in __setitem__
    type_name(self)
ValueError: Value for field "service" of asn1crypto.cms.SvceAuthInfo is not set
    while constructing asn1crypto.cms.SvceAuthInfo
```

I'll be pushing up a fix to this error. However, that won't help you if you are running a release from PyPI. In that case you'll need to call `.dump()` on the `GeneralName` before adding it to the `SvceAuthInfo`.

## Second Error

I haven't looked into this really, but I think you are passing incorrect parameters again.

**Comment by ftbarata** [comment]
@wbond  thank you a lot for reply. So, following your instructions:

```
'attributes': cms.AttCertAttribute({
                                                    'type': cms.AttCertAttributeType('authentication_info'),
                                                    'values': [cms.SvceAuthInfo({
                                                        'service': GeneralName('directory_name', Name.build({'common_name':'Test'})).dump(),
                                                        'ident': GeneralName('directory_name', Name.build({'common_name':'Test2'})).dump()
                                                    })]
                                                })
```
Gives
```
File "agent.py", line 153, in createCertificateOsCrypto
    'ident': GeneralName('directory_name', Name.build({'common_name':'Test2'})).dump()
  File "/root/sigcerta/.virtualenv/lib/python3.5/site-packages/asn1crypto/core.py", line 3170, in __init__
    raise e
  File "/root/sigcerta/.virtualenv/lib/python3.5/site-packages/asn1crypto/core.py", line 3154, in __init__
    self.__setitem__(key, value[key])
  File "/root/sigcerta/.virtualenv/lib/python3.5/site-packages/asn1crypto/core.py", line 3310, in __setitem__
    new_value = self._make_value(field_name, field_spec, value_spec, field_params, value)
  File "/root/sigcerta/.virtualenv/lib/python3.5/site-packages/asn1crypto/core.py", line 3537, in _make_value
    type_name(value_spec)
ValueError: Can not set a native python value to service, which has the choice type of asn1crypto.x509.GeneralName - value must be an instance of Asn1Value
    while constructing asn1crypto.cms.SvceAuthInfo
```

**Comment by wbond** [comment]
Don't pass the return value of `.dump()`, but assign values to a var, dump, the pass to SvceAuthInfo constructor.

**Comment by ftbarata** [comment]
@wbond I'm so sorry. It's not clear to me the correct form to do it. I hate disturbing you. If you could  give an example I'll stop disturbing you earlier... Or, if you already pushed the fix, I can try a pip upgrade or download the cms.py or the correct file you fixed...

**Comment by wbond** [comment]
9a5a0259885c0ccd610815aa4ec52afb1fd9554f fixes the bug

**Comment by ftbarata** [comment]
@wbond thanks to your fix I passed the attributes problem. But I suspect there is another bug. See:
These two forms:
```
'att_cert_validity_period': cms.AttCertValidityPeriod({
                                    'not_before_time': GeneralizedTime(parser.parse(NOT_VALID_BEFORE)),
                                    'not_after_time': GeneralizedTime(parser.parse(NOT_VALID_AFTER))
                                })
```
or 
```
'att_cert_validity_period': {
                                    'not_before_time': GeneralizedTime(parser.parse(NOT_VALID_BEFORE)),
                                    'not_after_time': GeneralizedTime(parser.parse(NOT_VALID_AFTER))
                                }
```
Gives:
```
File "agent.py", line 163, in createCertificateOsCrypto
    'not_after_time': GeneralizedTime(parser.parse(NOT_VALID_AFTER))
  File "/root/sigcerta/.virtualenv/lib/python3.5/site-packages/asn1crypto/core.py", line 3179, in __init__
    self.__setitem__(key, value[key])
  File "/root/sigcerta/.virtualenv/lib/python3.5/site-packages/asn1crypto/core.py", line 3335, in __setitem__
    new_value = self._make_value(field_name, field_spec, value_spec, field_params, value)
  File "/root/sigcerta/.virtualenv/lib/python3.5/site-packages/asn1crypto/core.py", line 3581, in _make_value
    new_value = value_spec(value, **field_params)
  File "/root/sigcerta/.virtualenv/lib/python3.5/site-packages/asn1crypto/core.py", line 3934, in __init__
    self.__setitem__(index, child)
  File "/root/sigcerta/.virtualenv/lib/python3.5/site-packages/asn1crypto/core.py", line 4091, in __setitem__
    new_value = self._make_value(value)
  File "/root/sigcerta/.virtualenv/lib/python3.5/site-packages/asn1crypto/core.py", line 4041, in _make_value
    return self._child_spec(value=value)
  File "/root/sigcerta/.virtualenv/lib/python3.5/site-packages/asn1crypto/core.py", line 3163, in __init__
    unused_keys = set(value.keys())
AttributeError: 'str' object has no attribute 'keys'
```
parser.parse(NOT_VALID_BEFORE) is a datetime.datetime object.

**Comment by wbond** [comment]
You are passing a single attribute where you should be sending a list or SequenceOf:

```python
'attributes': cms.AttCertAttribute({
```

You'll need to wrap that in a list.

**Comment by ftbarata** [comment]
Thank you God and @wbond ! That error is gone.

I am using python-pkcs11 for signing, so I have:
```
priv = session.get_key(object_class=pkcs11.constants.ObjectClass.PRIVATE_KEY)
signature = priv.sign(attribute_certificate_info_instance.dump(), mechanism=Mechanism.SHA256_RSA_PKCS)
attribute_certificate = cms.AttributeCertificateV2({
                                'ac_info': attribute_certificate_info_instance,
                                'signature_algorithm':  signed_digest_algo,
                                'signature': signature
                            })
```
I'm getting  AttributeError: 'str' object has no attribute 'keys' at the line below:
```
'signature': signature
```
Because the signature type  is bytes and your library requires OctetBitString.  Do you have any idea of how to do this conversion?

**Comment by wbond** [comment]
Can you provide the full backtrace? Are you using Python 2 or 3?

I just confirmed that if you pass a byte string (`str` in Python 2, `bytes` in Python 3) to `OctetBitString`, it works. Have you tried: `core.OctetBitString(signature)`?

**Comment by ftbarata** [comment]
I'm using python 3.5.5 !
```
temp_signature = priv.sign(attribute_certificate_info_instance.dump(), mechanism=Mechanism.SHA256_RSA_PKCS)
                            signature = OctetBitString(temp_signature)

                            attribute_certificate = cms.AttributeCertificateV2({
                                'ac_info': attribute_certificate_info_instance,
                                'signature_algorithm':  signed_digest_algo,
                                'signature': signature
                            })
```
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.5.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "agent.py", line 394, in run
    AUTHORITY_KEY_IDENTIFIER=hexadecimal_sha1_token_public_key
  File "agent.py", line 193, in createCertificateOsCrypto
    'signature': signature
  File "/root/sigcerta/.virtualenv/lib/python3.5/site-packages/asn1crypto/core.py", line 3179, in __init__
    self.__setitem__(key, value[key])
  File "/root/sigcerta/.virtualenv/lib/python3.5/site-packages/asn1crypto/core.py", line 3335, in __setitem__
    new_value = self._make_value(field_name, field_spec, value_spec, field_params, value)
  File "/root/sigcerta/.virtualenv/lib/python3.5/site-packages/asn1crypto/core.py", line 3581, in _make_value
    new_value = value_spec(value, **field_params)
  File "/root/sigcerta/.virtualenv/lib/python3.5/site-packages/asn1crypto/core.py", line 3163, in __init__
    unused_keys = set(value.keys())
AttributeError: 'str' object has no attribute 'keys'

```

**Comment by ftbarata** [comment]
The type of signature is <class 'asn1crypto.core.OctetBitString'> , but still not working

**Comment by wbond** [comment]
This error you are getting means you are passing in an incorrect data type. I've got extra checks that I can add to give you more help.

I'd double-check the values you are passing match the structure definition. So far passing the wrong parameters have been an issue a few times in this thread (in addition to the nested Choice bug).

**Comment by ftbarata** [comment]
You're right. It's the first time I have to understand documentation within the source code, so I'm not accostumed with this. I'm really sorry. So you mean that even the type of signature generated by pkcs11 device is bytes and doing OctetBitString(signature) seems fine to converting to asn1crypto.core.OctetBitString class, there is still some problem in this signature bytes. Is that you mean? If so, I will try to check what can be done with this signature object from pkcs11

**Comment by wbond** [comment]
No, I think another field has an error. Please try ecda20176f55d37021cbca1f6da9083a8e491197 and see if it highlights any issues. It should catch this error.

**Comment by ftbarata** [comment]
Ok! I've updated the entire asn1crypto code and ran again:
```
File "/root/sigcerta/.virtualenv/lib/python3.5/site-packages/asn1crypto/core.py", line 3179, in __init__
    self.__setitem__(key, value[key])
  File "/root/sigcerta/.virtualenv/lib/python3.5/site-packages/asn1crypto/core.py", line 3335, in __setitem__
    new_value = self._make_value(field_name, field_spec, value_spec, field_params, value)
  File "/root/sigcerta/.virtualenv/lib/python3.5/site-packages/asn1crypto/core.py", line 3590, in _make_value
    new_value = value_spec(value, **field_params)
  File "/root/sigcerta/.virtualenv/lib/python3.5/site-packages/asn1crypto/core.py", line 3163, in __init__
    unused_keys = set(value.keys())
AttributeError: 'str' object has no attribute 'keys'

```

**Comment by wbond** [comment]
You need to double check the data types of the definition and the data types of your data.

Perhaps call `.__class__` on your values and see what you are passing in.

 - `attribute_certificate_info_instance` must be an instance of `AttributeCertificateInfoV2`
 - `signed_digest_algo` must be an instance of `SignedDigestAlgorithm`
 - `signature` must be `OctetBitString` (which it is, otherwise there would be an error when creating the object two lines above)

**Comment by ftbarata** [comment]
THANK YOU SO MUCH @wbond . The error was because signed_digest_algo value I was passing in was str class. I fixed it and it worked!

You saved me. Many many thanks!  Please close this thread.
