### ISSUE TITLE
Add support for BER encoded BitString

### ISSUE THREAD

**Issue by joernheissler** [wbond/asn1crypto#147]
X.690 has an example for a BER encoded BitString with a nested structure (§8.6.4.2).
It looks like asn1crypto cannot parse this.

```python3
#!/usr/bin/env python

from asn1crypto.core import BitString
import re

der = bytes.fromhex(re.sub(r'\s+', '', '''
    23 80
        03 03 00 0a 3b
        03 05 04 5f 29 1c d0
    00 00
'''))

bstr = BitString.load(der)
print(bstr.native)
```

dumpasn1 shows as output:
```
   0 NDEF: BIT STRING {
   2    3:   BIT STRING
         :     '1101110001010000'B
   7    5:   BIT STRING 4 unused bits
         :     '1011001110001001010011111010'B
         :   }
```

Python program shows:
```
Traceback (most recent call last):
  File "./bitstr", line 13, in <module>
    bstr = BitString.load(der)
  File "/home/user/.venv/asn1crypto/lib/python3.8/site-packages/asn1crypto/core.py", line 230, in load
    value, _ = _parse_build(encoded_data, spec=spec, spec_params=kwargs, strict=strict)
  File "/home/user/.venv/asn1crypto/lib/python3.8/site-packages/asn1crypto/core.py", line 5393, in _parse_build
    info, new_pointer = _parse(encoded_data, encoded_len, pointer)
  File "/home/user/.venv/asn1crypto/lib/python3.8/site-packages/asn1crypto/parser.py", line 231, in _parse
    raise ValueError(_INSUFFICIENT_DATA_MESSAGE % (contents_end, data_len))
ValueError: Insufficient data - 66 bytes requested but only 16 available
```

**Comment by wbond** [comment]
It would seem there is a bug in the indefinite-encoding handling for BitString.
