### ISSUE TITLE
Error parsing asn1crypto.x509.TbsCertificate

### ISSUE THREAD

**Issue by zepengchen** [wbond/asn1crypto#180]
Test code:

```python
p = pathlib.Path('/xxxxx/6BC3C33F4D6EA0D626E1881ACC7F70AC.apk_FILES/META-INF/SUPERWAL.RSA')
data = p.read_bytes()

info = cms.ContentInfo.load(data)
signed_data = info['content']
for certificate in signed_data['certificates']:
    item = {}
    cert = x509.Certificate.load(certificate.contents)
    print(cert)
    tbs_certificate = cert['tbs_certificate']
```

Error Information
```
<asn1crypto.x509.Certificate 139859613693600 b'0\x82\x01\xad\xa0\x03\x02\x01\x02\x02\x04=\xd1\x97\x0c0\r\x06\t*\x86H\x86\xf7\r\x01\x01\x0b\x05\x000\x131\x110\x0f\x06\x03U\x04\x03\x13\x08superwal0\x1e\x17\r191213102929Z\x17\r441206102929Z0\x131\x110\x0f\x06\x03U\x04\x03\x13\x08superwal0\x82\x01"0\r\x06\t*\x86H\x86\xf7\r\x01\x01\x01\x05\x00\x03\x82\x01\x0f\x000\x82\x01\n\x02\x82\x01\x01\x00\x82@\x86("\x1b\x01\x98\x0f\xc2.hC\xe3(6\x9e\xb4\x14v\xc4v\xae\x93\xfa\x96\x88\x01\x9dK<\xe5}\xb8,\xc8c\x1cU\xdbd\xa40L%O\x94P\x0e_\xfd\x8c,\x89\xb8\x99\xb4\xc7h\x94\xe1D\x17B\xc5\x18/0j_\x82\xbc\x912\x8d\xdc\xe6\xf3v\xc5he\xa5\xd4\x94\xac\x90Y\xb5#\xd9"h\xd1\x8d\xa8\x9a\x96\x18(*l2D\x98\x08_\xc2J1m\xf8h)N&\xfb&\xe8\xe3\x8aHa\xa1 \x06\xfek\xb6\xcb\xb3a8\xbd\x10\xd1s\x80\x87[\xe5&>\x9bx\x9f\xccB:\xba`>C\x90Z\xado\xfa\xf5Y\x87\x9e\x9aa\x96\x96\x88\xc4\xe7\'\xe1A\xe9yc\xdaR\xb8\xf6\x03K\xa1\xc9\x04\xcd:\xb23=e\xbb\x13\xf2F\xdag\x0f\x05o\xcc\xc6\x93M$NQn\x9aV0d\xfdqAy\x11"\xe8\xceb\xc9qC\xc6*\xa4"\x99w)\x96\xce\x857\xd6\xf7\xc8%\xee\x12\xc1q\xd3\x9f-s\xad\x8eNs&G\x03rZ\x15\x02\x03\x01\x00\x01\xa3!0\x1f0\x1d\x06\x03U\x1d\x0e\x04\x16\x04\x14H?\xc2\x87\xd3,\x03#X$\xdf\x04\xee\xe5\xcf\xe4\x13\xee\xa9{'>
```

```
Traceback (most recent call last):
  File "/home/xxxxx/git/mr-dirty-backend/test1.py", line 13, in <module>
    tbs_certificate = cert['tbs_certificate']
  File "/home/xxxxx/.virtualenvs/p38/lib/python3.8/site-packages/asn1crypto/core.py", line 3514, in __getitem__
    raise e
  File "/home/xxxxx/.virtualenvs/p38/lib/python3.8/site-packages/asn1crypto/core.py", line 3509, in __getitem__
    return self._lazy_child(key)
  File "/home/xxxxx/.virtualenvs/p38/lib/python3.8/site-packages/asn1crypto/core.py", line 3456, in _lazy_child
    child = self.children[index] = _build(*child)
  File "/home/xxxxx/.virtualenvs/p38/lib/python3.8/site-packages/asn1crypto/core.py", line 5515, in _build
    raise ValueError(unwrap(
ValueError: Error parsing asn1crypto.x509.TbsCertificate - class should have been universal, but context was found
    while parsing asn1crypto.x509.Certificate`
```

asn1crypto Version: 1.3.0

Above code is success in asn1crypto-0.24.0, but throws exception at asn1crypto-1.0.0, asn1crypto-1.2.0 and asn1crypto-1.3.0

**Comment by wbond** [comment]
```
for certificate in signed_data['certificates']:
```
This will loop over the `cms.CertificateChoices` objects. To use this properly, you'll have to do something along these lines (untested):

```python
p = pathlib.Path('/xxxxx/6BC3C33F4D6EA0D626E1881ACC7F70AC.apk_FILES/META-INF/SUPERWAL.RSA')
data = p.read_bytes()

info = cms.ContentInfo.load(data)
signed_data = info['content']
for certificate_choice in signed_data['certificates']:
    item = {}
    cert = certificate_choice.chosen
    print(cert)
    tbs_certificate = cert['tbs_certificate']
```

**Comment by zepengchen** [comment]
Thank you very much.
Your code works fine in asn1crypto Version 1.3.0.
