### ISSUE TITLE
convert BitString to bytes[] ?

### ISSUE THREAD

**Issue by jeroenjacobs79** [wbond/asn1crypto#197]
It seems that `.native` of BitString returns a tuple of integers that are either 0 or 1.

Is there a way to get byte[] representation of this data? 

For example, public keys in EC keys are stored as a BitString. When I do `print(value.native)` representation, I get this:

```
(0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1)
```

I don't want a tuple of 520 bits, I want a tuple or list of 65 bytes. Is there a helper function available for this? Or another way to do this?

**Comment by joernheissler** [comment]
Hello,
how to reproduce this?
This code shows me a byte string:

```python
#!/usr/bin/env python3

from asn1crypto.keys import PublicKeyInfo
from asn1crypto.pem import unarmor

pub = PublicKeyInfo.load(unarmor(b"""
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEbqv6KMJKT3UPfN7Ee6sgrdH4Y8l5
1qGaGqJGqKZlcinHMQ8KZ9maT1+PCr7/3HeMR6bUvI+MCMTdEuVE5CX1sQ==
-----END PUBLIC KEY-----
""")[2])

print(pub["public_key"].native.hex())
```
==> `046eabfa28c24a4f750f7cdec47bab20add1f863c979d6a19a1aa246a8a6657229c7310f0a67d99a4f5f8f0abeffdc778c47a6d4bc8f8c08c4dd12e544e425f5b1`

**Comment by joernheissler** [comment]
There are types `IntegerOctetString` and `OctetBitString` to use integers and bit strings as byte strings.

**Comment by jeroenjacobs79** [comment]
```
#!/usr/bin/env python
from __future__ import print_function
from asn1crypto.core import Sequence, OctetString
from cryptography.hazmat.primitives.asymmetric.ec import generate_private_key, EllipticCurvePrivateKey, SECP256K1, EllipticCurvePrivateKeyWithSerialization
from cryptography.hazmat.primitives.serialization import Encoding, PrivateFormat, PublicFormat, NoEncryption
from cryptography.hazmat.primitives import hashes


def gen_key():
    full_key = generate_private_key(SECP256K1)
    priv = full_key.private_bytes(Encoding.DER, PrivateFormat.TraditionalOpenSSL, NoEncryption())
    public = full_key.public_key().public_bytes(Encoding.DER, PublicFormat.SubjectPublicKeyInfo)
    pem_file = full_key.private_bytes(Encoding.PEM, PrivateFormat.TraditionalOpenSSL, NoEncryption())
    return priv, public

def main():
    priv, public = gen_key()
    # extract private key in suitable format
    parsed = Sequence.load(priv)
    priv_text="".join(["%02x" % x for x in parsed[1].native])
    # extract public key in suitable format
    parsed = Sequence.load(public)
    print(parsed[1].native.hex())


    
if __name__ == '__main__':
    main()

```

This gives me the following error:

```
Traceback (most recent call last):
  File "./testme.py", line 28, in <module>
    main()
  File "./testme.py", line 23, in main
    print(parsed[1].native.hex())
AttributeError: 'tuple' object has no attribute 'hex'
```

I will try with `asn1crypto.keys` module, but I find it weird that BitString.native doesn't have a hex() function. This should be useful there as well.

**Comment by joernheissler** [comment]
When you've got a `BitString`, then you could cast it like this:
`print(pub[1].cast(OctetBitString).native.hex())`

(Don't do this!)

Instead of using the primitive types like `Sequence` directly, you should use the higher level classes like `PublicKeyInfo`.

**Comment by jeroenjacobs79** [comment]
`print(pub["public_key"].native.hex())` seems to include the tag number (0x04 in this case) as well. Is this correct behaviour? Technically it's not part of the public key.

**Comment by joernheissler** [comment]
See https://www.secg.org/sec1-v2.pdf §2.3.3, 3.3.

**Comment by jeroenjacobs79** [comment]
Thanks, will look into that.

One more thing... While your suggestion seems to work for public keys, I'm getting errors when I try the same with PrivateKeyInfo.

To illustrate, this works:

```
#!/usr/bin/env python
from __future__ import print_function
from asn1crypto.core import Sequence, OctetString
from asn1crypto.keys import PublicKeyInfo
from cryptography.hazmat.primitives.asymmetric.ec import generate_private_key, EllipticCurvePrivateKey, SECP256K1, EllipticCurvePrivateKeyWithSerialization
from cryptography.hazmat.primitives.serialization import Encoding, PrivateFormat, PublicFormat, NoEncryption
from cryptography.hazmat.primitives import hashes


def gen_key():
    full_key = generate_private_key(SECP256K1)
    priv = full_key.private_bytes(Encoding.DER, PrivateFormat.TraditionalOpenSSL, NoEncryption())
    public = full_key.public_key().public_bytes(Encoding.DER, PublicFormat.SubjectPublicKeyInfo)
    pem_file = full_key.private_bytes(Encoding.PEM, PrivateFormat.TraditionalOpenSSL, NoEncryption())
    return priv, public

def main():
    priv_der, public_der = gen_key()
    # extract private key in suitable format
    priv_info = Sequence.load(priv_der)
    priv_hex="".join(["%02x" % x for x in priv_info[1].native])
    print(priv_hex)
    # extract public key in suitable format
    public_info = PublicKeyInfo.load(public_der)
    public_hex = public_info["public_key"].native.hex()
    print(public_hex)


    
if __name__ == '__main__':
    main()
```

However, this gives an error:

```
#!/usr/bin/env python
from __future__ import print_function
from asn1crypto.core import Sequence, OctetString
from asn1crypto.keys import PublicKeyInfo, PrivateKeyInfo
from cryptography.hazmat.primitives.asymmetric.ec import generate_private_key, EllipticCurvePrivateKey, SECP256K1, EllipticCurvePrivateKeyWithSerialization
from cryptography.hazmat.primitives.serialization import Encoding, PrivateFormat, PublicFormat, NoEncryption
from cryptography.hazmat.primitives import hashes


def gen_key():
    full_key = generate_private_key(SECP256K1)
    priv = full_key.private_bytes(Encoding.DER, PrivateFormat.TraditionalOpenSSL, NoEncryption())
    public = full_key.public_key().public_bytes(Encoding.DER, PublicFormat.SubjectPublicKeyInfo)
    pem_file = full_key.private_bytes(Encoding.PEM, PrivateFormat.TraditionalOpenSSL, NoEncryption())
    return priv, public

def main():
    priv_der, public_der = gen_key()
    # extract private key in suitable format
    priv_info = PrivateKeyInfo.load(priv_der)
    priv_hex=priv_info["private_key"].native.hex()
    print(priv_hex)
    # extract public key in suitable format
    public_info = PublicKeyInfo.load(public_der)
    public_hex = public_info["public_key"].native.hex()
    print(public_hex)


    
if __name__ == '__main__':
    main()
```

This results in this error:

```
Traceback (most recent call last):
  File "./testme.py", line 31, in <module>
    main()
  File "./testme.py", line 21, in main
    priv_hex=priv_info["private_key"].native.hex()
  File "/Users/jeroenjacobs/.pyenv/versions/eth/lib/python3.8/site-packages/asn1crypto/core.py", line 3508, in __getitem__
    self._parse_children()
  File "/Users/jeroenjacobs/.pyenv/versions/eth/lib/python3.8/site-packages/asn1crypto/core.py", line 3988, in _parse_children
    raise e
  File "/Users/jeroenjacobs/.pyenv/versions/eth/lib/python3.8/site-packages/asn1crypto/core.py", line 3895, in _parse_children
    cls._precomputed_specs[field] or self._determine_spec(field))
  File "/Users/jeroenjacobs/.pyenv/versions/eth/lib/python3.8/site-packages/asn1crypto/core.py", line 3733, in _determine_spec
    spec_override = callback(self)
  File "/Users/jeroenjacobs/.pyenv/versions/eth/lib/python3.8/site-packages/asn1crypto/keys.py", line 704, in _private_key_spec
    algorithm = self['private_key_algorithm']['algorithm'].native
  File "/Users/jeroenjacobs/.pyenv/versions/eth/lib/python3.8/site-packages/asn1crypto/core.py", line 3536, in __getitem__
    raise e
  File "/Users/jeroenjacobs/.pyenv/versions/eth/lib/python3.8/site-packages/asn1crypto/core.py", line 3531, in __getitem__
    return self._lazy_child(key)
  File "/Users/jeroenjacobs/.pyenv/versions/eth/lib/python3.8/site-packages/asn1crypto/core.py", line 3478, in _lazy_child
    child = self.children[index] = _build(*child)
  File "/Users/jeroenjacobs/.pyenv/versions/eth/lib/python3.8/site-packages/asn1crypto/core.py", line 5551, in _build
    raise ValueError(unwrap(
ValueError: Error parsing asn1crypto.keys.PrivateKeyAlgorithm - method should have been constructed, but primitive was found
    while parsing asn1crypto.keys.PrivateKeyInfo
    while parsing asn1crypto.keys.PrivateKeyInfo
```

I also tried with `ECPrivateKey` but there `native.hex()` doesn't exist either...

**Comment by joernheissler** [comment]
Don't use `PrivateFormat.TraditionalOpenSSL` but use PKCS8 instead!
Or if you really need to use "traditional" (headerless), use the correct asn1crypto class for this format. I think it's `keys.ECPrivateKey`.

**Comment by jeroenjacobs79** [comment]
Yeah, PKCS8 format for private key seems to work.

But it seems that both PrivateKeyInfo and ECPrivateKey lack the `native.hex()` function. So yeah, I'll figure out some conversion myself...

On a sidenote, the issue I linked seems to be correct `ECPrivateKey` works with `TraditionalOpenSSL` and `PrivateKeyInfo` only works with `PKCS8`. Not sure if this is a bug or not.

**Comment by joernheissler** [comment]
> `ECPrivateKey` works with `TraditionalOpenSSL` and `PrivateKeyInfo` only works with `PKCS8`. Not sure if this is a bug or not.

Not a bug.

> native.hex() doesn't exist either...

You could cast the key to an OctetString to get the bytes representation. Then you could use `hex()` on its value. But ec private keys really are integers (or more specific congruence classes) from a mathematical point of view.
