### ISSUE TITLE
Cannot create cms.SignedData

### ISSUE THREAD

**Issue by joernheissler** [wbond/asn1crypto#22]
I'm trying to create a CMS structure (ContentInfo containing SignedData), but don't know how. The following fails. My mistake or a bug?

    #!/usr/bin/python3
    from asn1crypto import cms
    cms.SignedData({
        'version': 'v1',
        'encap_content_info': {
            'content_type': 'data',
            'content': b'Hello',
        }
    })

Error:

    Traceback (most recent call last):
      File "sd.py", line 7, in <module>
        'content': b'Hello',
      File "/usr/lib/python3/dist-packages/asn1crypto/core.py", line 2646, in __init__
        raise e
      File "/usr/lib/python3/dist-packages/asn1crypto/core.py", line 2641, in __init__
        self.__setitem__(key, value[key])
      File "/usr/lib/python3/dist-packages/asn1crypto/core.py", line 2786, in __setitem__
        new_value = self._make_value(field_name, field_spec, value_spec, field_params, value)
      File "/usr/lib/python3/dist-packages/asn1crypto/core.py", line 2998, in _make_value
        is_any = issubclass(field_spec, Any)
    TypeError: issubclass() arg 1 must be a class
        while constructing asn1crypto.cms.SignedData

field_spec is None in core.py:2998.
I assume it comes from SignedData._fields where it says None for encap_content_info.

**Comment by wbond** [comment]
This should be resolved by 3aa0dca1adfc01af78dc2a2692b1b4b98ab8c800

**Comment by joernheissler** [comment]
Thank you!
