### ISSUE TITLE
ocsp crash ValueError: not enough values to unpack (expected 3, got 2)

### ISSUE THREAD

**Issue by gudder** [wbond/asn1crypto#237]
Run the py script for the first time to generate a summary.

`
async def gen_digest(dic):
    prep_digest, signed_attrs, psi, output = await prep_doc(input_pdf, cert_path, timestamper_url, timestamper_timeout)
    with open('prep_digest.data', 'wb') as outf:
        pickle.dump(prep_digest, outf)
    with open('signed_attrs.data', 'wb') as outf:
        pickle.dump(signed_attrs, outf)    
    with open('psi.data', 'wb') as outf:
        pickle.dump(psi, outf)
    with open('output.data', 'wb') as outf:
        pickle.dump(output, outf)
`

Run the py script to execute signature for the second time.

`
async def sign_pdf(dic):
    with open('prep_digest.data', 'rb') as inf:
        prep_digest = pickle.load(inf)
    with open('signed_attrs.data', 'rb') as inf:
        signed_attrs = pickle.load(inf)    
    with open('psi.data', 'rb') as inf:
        psi = pickle.load(inf)
    with open('output.data', 'rb') as inf:
        output = pickle.load(inf)
`

Traceback (most recent call last):
File ".\interrupted_signing.py", line 263, in
main()
File ".\interrupted_signing.py", line 257, in main
outf.write(asyncio.run(sign_pdf(dic)).getvalue())
File "C:\Python38\lib\asyncio\runners.py", line 44, in run
return loop.run_until_complete(main)
File "C:\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
return future.result()
File ".\interrupted_signing.py", line 230, in sign_pdf
await proceed_with_signing(signing_certificate, prep_digest, signed_attrs, sig_value, new_psi, new_output)
File ".\interrupted_signing.py", line 85, in proceed_with_signing
await PdfTBSDocument.async_finish_signing(
File "C:\Python38\lib\site-packages\pyhanko\sign\signers\pdf_signer.py", line 2237, in async_finish_signing
await post_sign.post_signature_processing(
File "C:\Python38\lib\site-packages\pyhanko\sign\signers\pdf_signer.py", line 2324, in post_signature_processing
validation.DocumentSecurityStore.supply_dss_in_writer(
File "C:\Python38\lib\site-packages\pyhanko\sign\validation\dss.py", line 445, in supply_dss_in_writer
dss.register_vri(
File "C:\Python38\lib\site-packages\pyhanko\sign\validation\dss.py", line 211, in register_vri
ocsp_refs = set(
File "C:\Python38\lib\site-packages\pyhanko\sign\validation\dss.py", line 133, in _cms_objects_to_streams
obj_bytes = obj.dump()
File "C:\Python38\lib\site-packages\asn1crypto\core.py", line 4124, in dump
for index, (field_name, _, params) in enumerate(self._fields):
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by Varkal** [comment]
Hey @nengxingxu ! 

Have you found a solution to this issue ? I have a similar problem 

Thanks you !
