### ISSUE TITLE
CI Test throw error due to expired certificate

### ISSUE THREAD

**Issue by Anti-Myon** [wbond/asn1crypto#253]
The CI-Test throws an error due to an certificate which expires on 2023-01-01 00:00:00Z:

```
Running tests from other modularcrypto packages
..............................................................................................................................................s......E...EE..........E..EE.....E........................................................................................................................................................................................................................................
======================================================================
ERROR: test_tls_connect_dh1024 (oscrypto.tests.test_tls.TLSTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "../oscrypto/tests/unittest_data.py", line 51, in generated_test_function
    original_function(self, *params)
  File "../oscrypto/tests/test_tls.py", line 75, in wrapped
    f(*args)
  File "../oscrypto/tests/test_tls.py", line 102, in tls_connect
    connection = tls.TLSSocket(hostname, port, session=session)
  File "/home/circleci/oscrypto/oscrypto/_openssl/tls.py", line 456, in __init__
    self._handshake()
  File "/home/circleci/oscrypto/oscrypto/_openssl/tls.py", line 667, in _handshake
    raise_expired_not_yet_valid(cert)
  File "/home/circleci/oscrypto/oscrypto/_tls.py", line 509, in raise_expired_not_yet_valid
    raise TLSVerificationError(message, certificate)
oscrypto.errors.TLSVerificationError: Server certificate verification failed - certificate expired 2023-01-01 00:00:00Z
```
Could you please update the test certificate. 
Thanks

**Comment by wbond** [comment]
Master has been green-ified and CI fixed to work with the latest and greatest CI images, Python versions and example certificates.
