### ISSUE TITLE
Error parsing valid EncryptedContentInfo

### ISSUE THREAD

**Issue by natzlob** [wbond/asn1crypto#264]
I receive valid CMS EncryptedContentInfo bytes, which I call `encrypted_content_info`. From the EncryptedContentInfo, I can get the encrypted algorithm with `encrypted_content_info['content_encryption_algorithm']`. However, there is an error when extracting the EncryptedContent from encrypted_content_info. The error is:
```
encrypted_content_bytes = encrypted_content_info['encrypted_content']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../python3.7/site-packages/asn1crypto/core.py", line 3536, in __getitem__
    raise e
  File ".../python3.7/site-packages/asn1crypto/core.py", line 3531, in __getitem__
    return self._lazy_child(key)
  File ".../python3.7/site-packages/asn1crypto/core.py", line 3478, in _lazy_child
    child = self.children[index] = _build(*child)
  File ".../python3.7/site-packages/asn1crypto/core.py", line 5561, in _build
    METHOD_NUM_TO_NAME_MAP.get(method, method)
ValueError: Error parsing asn1crypto.core.OctetString - method should have been primitive, but constructed was found
    while parsing asn1crypto.cms.EncryptedContentInfo
```

When I take the EncryptedContentInfo, write it to file and use `openssl asn1parse` to parse it as follows:
`openssl asn1parse -inform der -in encrypted_content_info.ber`, 
the encrypted content can be successfully extracted. If I take the encrypted content obtained from `openssl asn1parse`, I can then decrypt it successfully etc. This means there is a problem with the way `asn1crypto` parses this CMS. This seems like a bug with the package.

Is there another way this content should be extracted using `asn1crypto`? Is there a fix for this problem? Please assist.

Some additional info is that the ContentType of the EncryptedContentInfo is simply `data`.

**Comment by MatthiasValvekens** [comment]
Judging from the file extension and the error message, I guess that your payload uses the constructed (i.e. segmented) representation to encode the octet string with the encrypted content. This is legal in BER, but not in DER, and IIRC asn1crypto doesn't support constructed strings at all (can't check now, though).

They're very rare in the wild due to them being disallowed in DER, which is by far the most common ASN.1 encoding flavour.

It's hard to say for sure without having the actual payload in front of me, but I guess this is it. FWIW, I've successfully used asn1crypto with encrypted CMS messages in the past (all DER, though).

**Comment by MatthiasValvekens** [comment]
Ah, it's actually different: the CMS spec mandated implicit tagging for the encryptedContent field; your payload has explicit tagging there.


The reason why this shows up as an encoding method error is because explicit values are always constructed, whereas a "naked" octet string would be primitive.

So the data is invalid, but you can work around it by copy-pasting asn1crypto's EncryptedContentInfo class and replacing the implicit tag with explicit... That won't work on valid data, though... (:

**Comment by natzlob** [comment]
Thanks. Is there a way to define the class to ignore the implicit/explicit tag altogether and make it compatible with data either correctly or incorrectly tagged?

**Comment by grk-it** [comment]
@natzlob there's a PR now that takes care of this issue: https://github.com/smallstep/pkcs7/pull/9

**Comment by jinhua115** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
