### ISSUE TITLE
Error encoding NameConstraints: UnicodeError: label empty or too long

### ISSUE THREAD

**Issue by joernheissler** [wbond/asn1crypto#34]
Related to #33:
```
#!/usr/bin/env python3

from asn1crypto.x509 import NameConstraints

der = bytes.fromhex(
    '303ea03c300582032e6772300582032e6575300682042e656475300682042e6f7267300581032e6772300581032e6575300681042e656475300681042e6f7267'
)
cs = NameConstraints.load(der)
cs.dump(force=True)
```

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/encodings/idna.py", line 165, in encode
    raise UnicodeError("label empty or too long")
UnicodeError: label empty or too long

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./name.py", line 9, in <module>
    cs.dump(force=True)
  File "/home/joern/env/lib/python3.5/site-packages/asn1crypto-0.21.1-py3.5.egg/asn1crypto/core.py", line 3512, in dump
  File "/home/joern/env/lib/python3.5/site-packages/asn1crypto-0.21.1-py3.5.egg/asn1crypto/core.py", line 3081, in _set_contents
  File "/home/joern/env/lib/python3.5/site-packages/asn1crypto-0.21.1-py3.5.egg/asn1crypto/core.py", line 3975, in dump
  File "/home/joern/env/lib/python3.5/site-packages/asn1crypto-0.21.1-py3.5.egg/asn1crypto/core.py", line 3842, in _set_contents
  File "/home/joern/env/lib/python3.5/site-packages/asn1crypto-0.21.1-py3.5.egg/asn1crypto/core.py", line 3512, in dump
  File "/home/joern/env/lib/python3.5/site-packages/asn1crypto-0.21.1-py3.5.egg/asn1crypto/core.py", line 3081, in _set_contents
  File "/home/joern/env/lib/python3.5/site-packages/asn1crypto-0.21.1-py3.5.egg/asn1crypto/core.py", line 1107, in dump
  File "/home/joern/env/lib/python3.5/site-packages/asn1crypto-0.21.1-py3.5.egg/asn1crypto/core.py", line 1483, in dump
  File "/home/joern/env/lib/python3.5/site-packages/asn1crypto-0.21.1-py3.5.egg/asn1crypto/core.py", line 1556, in set
UnicodeError: encoding with 'idna' codec failed (UnicodeError: label empty or too long)
```

```
  0  62: SEQUENCE {
  2  60: . [0] {
  4   5: . . SEQUENCE {
  6   3: . . . [2] 2E 67 72                   .gr
       : . . . }
 11   5: . . SEQUENCE {
 13   3: . . . [2] 2E 65 75                   .eu
       : . . . }
 18   6: . . SEQUENCE {
 20   4: . . . [2] '.edu'
       : . . . }
 26   6: . . SEQUENCE {
 28   4: . . . [2] '.org'
       : . . . }
 34   5: . . SEQUENCE {
 36   3: . . . [1] 2E 67 72                   .gr
       : . . . }
 41   5: . . SEQUENCE {
 43   3: . . . [1] 2E 65 75                   .eu
       : . . . }
 48   6: . . SEQUENCE {
 50   4: . . . [1] '.edu'
       : . . . }
 56   6: . . SEQUENCE {
 58   4: . . . [1] '.org'
       : . . . }
       : . . }
       : . }
```

**Comment by wbond** [comment]
Fixed by ed82e3f593b9bc5c89a116b8f9116b226cecd614
