### ISSUE TITLE
accented dir + unicode str mismatch

### ISSUE THREAD

**Issue by DomCharn** [wbond/asn1crypto#41]
Met issue when upgrading paramiko 1.15 to 2.2.1 (Windows10 + Python 2.7.1)

In the sequence the following : "from asn1crypto.algos import DSASignature"  entails Unicode Error 
The identified cause :
  in the $PATH we got the  " C:\Users\dom\Vic clé USB\Downloads\cmder_mini\bin;" Dir.
  when the instruction libcrypto_path = find_library('crypto') is executed we have the previous Dir (str) + 'crypto' coded as unicode involving the error in 'fname = os.path.join(directory, name)'

Wishing not to modify the code  the bypass was to change directory's name

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\python271\lib\site-packages\asn1crypto\algos.py", line 23, in <module>
    from ._int import fill_width
  File "C:\python271\lib\site-packages\asn1crypto\_int.py", line 56, in <module>
    from ._perf._big_num_ctypes import libcrypto
  File "C:\python271\lib\site-packages\asn1crypto\_perf\_big_num_ctypes.py", line 31, in <module>
    libcrypto_path = find_library('crypto')
  File "C:\python271\lib\ctypes\util.py", line 54, in find_library
    fname = os.path.join(directory, name)
  File "C:\python271\lib\ntpath.py", line 85, in join
    result_path = result_path + p_path
  File "C:\python271\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 17: invalid continuation byte
>>>

**Comment by wbond** [comment]
This should be resolved by 64ab19707acb644772a9ac3d94479fbe79b49365

**Comment by overfl0** [comment]
Hello!

When could we expect a new release on pypi with this fix merged?

**Comment by maxbelanger** [comment]
Any chance this will be released soon?

**Comment by wbond** [comment]
Version 0.23.0 was released last Friday
