### ISSUE TITLE
ECPrivateKey creation

### ISSUE THREAD

**Issue by ofek** [wbond/asn1crypto#43]
Say I have a 256 bit secret and its associated secp256k1 serialized public key, how can I convert to DER? Specifically, I'm using this as a reference: [https://github.com/ofek/coincurve/blob/master/tests/samples.py](https://github.com/ofek/coincurve/blob/master/tests/samples.py)

**Comment by joernheissler** [comment]
Can you provide example input values and an example how your output file shall look like?

**Comment by ofek** [comment]
@joernheissler @wbond I want

`PRIVATE_KEY_BYTES = b'\xc2\x8a\x9f\x80s\x8fw\rRx\x03\xa5f\xcfo\xc3\xed\xf6\xce\xa5\x86\xc4\xfcJR#\xa5\xady~\x1a\xc3'`
or
`PRIVATE_KEY_NUM = 87993618360805341115891506172036624893404292644470266399436498750715784469187`

plus

`PUBLIC_KEY_COMPRESSED = b"\x03=\\(u\xc9\xbd\x11hu\xa7\x1a]\xb6L\xff\xcb\x139k\x16=\x03\x9b\x1d\x93'\x82H\x91\x80C4"`
or
`PUBLIC_KEY_UNCOMPRESSED = b"\x04=\\(u\xc9\xbd\x11hu\xa7\x1a]\xb6L\xff\xcb\x139k\x16=\x03\x9b\x1d\x93'\x82H\x91\x80C4v\xa45**\xdd\x00\xeb\xb0\xd5\xc9LQ[r\xeb\x10\xf1\xfd\x8f?\x03\xb4/J+%[\xfc\x9a\xa9\xe3"`

to give me this:

[https://github.com/ofek/coincurve/blob/master/tests/samples.py#L2](https://github.com/ofek/coincurve/blob/master/tests/samples.py#L2)

**Comment by wbond** [comment]
It looks like we need to add the OID for ‘secp256k1’ at https://github.com/wbond/asn1crypto/blob/master/asn1crypto/keys.py#L371.

That said, something like this should work:

```python
asn1crypto.keys.ECPrivateKey({
    ‘version’: 'ecPrivkeyVer1’,
    ‘private_key’: PRIVATE_KEY_NUM,
    ‘parameters’: {’named’: ‘1.3.132.0.10’},
    ‘public_key’: asn1crypto.keys.ECPointBitString.from_coords(PUBLIC_KEY_X, PUBLIC_KEY_Y)
})
```

I haven’t tested it, but I believe that should do it.

**Comment by ofek** [comment]
@wbond Getting:

```
Python 3.5.3 | packaged by conda-forge | (default, Feb  9 2017, 15:12:38) [MSC v.1900 64 bit (AMD64)] on win32                                                
Type "help", "copyright", "credits" or "license" for more information.                                                                                        
>>> from asn1crypto import keys                                                                                                                               
>>> keys.ECPrivateKey({'version': 'ecPrivkeyVer1','private_key': 87993618360805341115891506172036624893404292644470266399436498750715784469187,'parameters': {
'named': '1.3.132.0.10'}, 'public_key': keys.ECPointBitString.from_coords(27753912938952041417634381842191885283234814940840273460372041880794577257268, 53663
045980837260634637807506183816949039230809110041985901491152185762425315)})                                                                                   
Traceback (most recent call last):                                                                                                                            
  File "<stdin>", line 1, in <module>                                                                                                                         
  File "C:\Users\Ofek\Desktop\q\Miniconda3\envs\curve\lib\site-packages\asn1crypto\core.py", line 3099, in __init__                                           
    raise e                                                                                                                                                   
  File "C:\Users\Ofek\Desktop\q\Miniconda3\envs\curve\lib\site-packages\asn1crypto\core.py", line 3083, in __init__                                           
    self.__setitem__(key, value[key])                                                                                                                         
  File "C:\Users\Ofek\Desktop\q\Miniconda3\envs\curve\lib\site-packages\asn1crypto\core.py", line 3239, in __setitem__                                        
    new_value = self._make_value(field_name, field_spec, value_spec, field_params, value)                                                                     
  File "C:\Users\Ofek\Desktop\q\Miniconda3\envs\curve\lib\site-packages\asn1crypto\core.py", line 3466, in _make_value                                        
    type_name(value_spec)                                                                                                                                     
ValueError: Can not set a native python value to parameters, which has the choice type of asn1crypto.keys.ECDomainParameters \u2013 value must be an instance 
of Asn1Value                                                                                                                                                  
    while constructing asn1crypto.keys.ECPrivateKey                                                                                                           
>>>                                                                                                                                                           
```

**Comment by wbond** [comment]
Try wrapping `asn1crypto.keys.ECDomainParameters()` around `{'named': '1.3.132.0.10'}`.

**Comment by ofek** [comment]
@wbond That works thanks! Though it produces different output than https://github.com/pyca/cryptography

```
>>> keys.ECPrivateKey({'version': 'ecPrivkeyVer1', 'private_key': 87993618360805341115891506172036624893404292644470266399436498750715784469187,'parameters': 
keys.ECDomainParameters({'named': '1.3.132.0.10'}), 'public_key': keys.ECPointBitString.from_coords(2775391293895204141763438184219188528323481494084027346037
2041880794577257268, 53663045980837260634637807506183816949039230809110041985901491152185762425315)}).dump()                                                  
b"0t\x02\x01\x01\x04 \xc2\x8a\x9f\x80s\x8fw\rRx\x03\xa5f\xcfo\xc3\xed\xf6\xce\xa5\x86\xc4\xfcJR#\xa5\xady~\x1a\xc3\xa0\x07\x06\x05+\x81\x04\x00\n\xa1D\x03B\x0
0\x04=\\(u\xc9\xbd\x11hu\xa7\x1a]\xb6L\xff\xcb\x139k\x16=\x03\x9b\x1d\x93'\x82H\x91\x80C4v\xa45**\xdd\x00\xeb\xb0\xd5\xc9LQ[r\xeb\x10\xf1\xfd\x8f?\x03\xb4/J+%
[\xfc\x9a\xa9\xe3"                                                                                                                                            
>>>                                                                                                                                                           
```

**Comment by wbond** [comment]
Is cryptography outputting ECPrivateKey, or PrivateKeyInfo?

If you provide the output of both, I can look into why they are different.

**Comment by ofek** [comment]
Using https://cryptography.io/en/latest/hazmat/primitives/asymmetric/ec/#cryptography.hazmat.primitives.asymmetric.ec.EllipticCurvePrivateKeyWithSerialization.private_bytes like this:

```
private_key.private_bytes(
    encoding=Encoding.DER,
    format=PrivateFormat.PKCS8,
    encryption_algorithm=NOENCRYPTION
)
```

**Comment by wbond** [comment]
Ah, PKCS#8 would be utilizing `asn1crypto.keys.PrivateKeyInfo()` to wrap the `ECPrivateKey`.

**Comment by ofek** [comment]
Getting closer :)

```
>>> keys.PrivateKeyInfo(keys.ECPrivateKey({'version': 'ecPrivkeyVer1', 'private_key': 879936183608053411158915061720366248934042926444702663994364987507157844
69187,'parameters': keys.ECDomainParameters({'named': '1.3.132.0.10'}), 'public_key': keys.ECPointBitString.from_coords(27753912938952041417634381842191885283
234814940840273460372041880794577257268, 53663045980837260634637807506183816949039230809110041985901491152185762425315)})).dump()                             
Traceback (most recent call last):                                                                                                                            
  File "<stdin>", line 1, in <module>                                                                                                                         
  File "C:\Users\Ofek\Desktop\q\Miniconda3\envs\curve\lib\site-packages\asn1crypto\core.py", line 3067, in __init__                                           
    unused_keys = set(value.keys())                                                                                                                           
AttributeError: 'ECPrivateKey' object has no attribute 'keys'                                                                                                 
>>>                                                                                                                                                           
```

**Comment by wbond** [comment]
Oh, no, you'll need to pass in a dict with values for the sequence: https://github.com/wbond/asn1crypto/blob/master/asn1crypto/keys.py#L491-L502. You'll need to look at the URL in the doc comment to figure out the correct version. I don't believe you'll need the `attributes` field.

**Comment by ofek** [comment]
```
>>> keys.PrivateKeyInfo({'version': 0, 'private_key_algorithm': keys.PrivateKeyAlgorithm({'algorithm': '1.2.840.10045.2.1'}), 'private_key': pk_dump})
Traceback (most recent call last):                                                                                                                    
  File "<stdin>", line 1, in <module>                                                                                                                 
  File "C:\Users\Ofek\Desktop\q\Miniconda3\envs\curve\lib\site-packages\asn1crypto\core.py", line 3083, in __init__                                   
    self.__setitem__(key, value[key])                                                                                                                 
  File "C:\Users\Ofek\Desktop\q\Miniconda3\envs\curve\lib\site-packages\asn1crypto\core.py", line 3237, in __setitem__                                
    field_name, field_spec, value_spec, field_params, _ = self._determine_spec(key)                                                                   
  File "C:\Users\Ofek\Desktop\q\Miniconda3\envs\curve\lib\site-packages\asn1crypto\core.py", line 3404, in _determine_spec                            
    spec_override = callback(self)                                                                                                                    
  File "C:\Users\Ofek\Desktop\q\Miniconda3\envs\curve\lib\site-packages\asn1crypto\keys.py", line 509, in _private_key_spec                           
    }[algorithm]                                                                                                                                      
KeyError: '1.2.840.10045.2.1'                                                                                                                         
>>>                                                                                                                                                   
```

**Comment by ofek** [comment]
@wbond Ok I had to pass 'ec'. It is closer to pyca/cryptography but not quite:

```
>>> pk = keys.ECPrivateKey({'version': 'ecPrivkeyVer1', 'private_key': 87993618360805341115891506172036624893404292644470266399436498750715784469187,'paramete
rs': keys.ECDomainParameters({'named': '1.3.132.0.10'}), 'public_key': keys.ECPointBitString.from_coords(27753912938952041417634381842191885283234814940840273
460372041880794577257268, 53663045980837260634637807506183816949039230809110041985901491152185762425315)})                                                    
>>> keys.PrivateKeyInfo({'version': 0, 'private_key_algorithm': keys.PrivateKeyAlgorithm({'algorithm': 'ec'}), 'private_key': pk}).dump()                     
b"0\x81\x86\x02\x01\x000\t\x06\x07*\x86H\xce=\x02\x01\x04v0t\x02\x01\x01\x04 \xc2\x8a\x9f\x80s\x8fw\rRx\x03\xa5f\xcfo\xc3\xed\xf6\xce\xa5\x86\xc4\xfcJR#\xa5\x
ady~\x1a\xc3\xa0\x07\x06\x05+\x81\x04\x00\n\xa1D\x03B\x00\x04=\\(u\xc9\xbd\x11hu\xa7\x1a]\xb6L\xff\xcb\x139k\x16=\x03\x9b\x1d\x93'\x82H\x91\x80C4v\xa45**\xdd\
x00\xeb\xb0\xd5\xc9LQ[r\xeb\x10\xf1\xfd\x8f?\x03\xb4/J+%[\xfc\x9a\xa9\xe3"                                                                                    
>>>                                                                                                                                                           
```

**Comment by ofek** [comment]
@wbond Here is a full example of getting DER using https://github.com/pyca/cryptography >= 1.6:

```
Python 3.5.3 | packaged by conda-forge | (default, Feb  9 2017, 15:12:38) [MSC v.1900 64 bit (AMD64)] on win32                                                
Type "help", "copyright", "credits" or "license" for more information.                                                                                        
>>> from cryptography.hazmat.backends import default_backend                                                                                                  
>>> from cryptography.hazmat.primitives.asymmetric.ec import SECP256K1, derive_private_key                                                                    
>>> from cryptography.hazmat.primitives.serialization import Encoding, NoEncryption, PrivateFormat                                                            
>>>                                                                                                                                                           
>>> private_key = derive_private_key(87993618360805341115891506172036624893404292644470266399436498750715784469187, SECP256K1(), default_backend())           
>>> private_key.private_bytes(encoding=Encoding.DER, format=PrivateFormat.PKCS8, encryption_algorithm=NoEncryption())                                         
b"0\x81\x84\x02\x01\x000\x10\x06\x07*\x86H\xce=\x02\x01\x06\x05+\x81\x04\x00\n\x04m0k\x02\x01\x01\x04 \xc2\x8a\x9f\x80s\x8fw\rRx\x03\xa5f\xcfo\xc3\xed\xf6\xce
\xa5\x86\xc4\xfcJR#\xa5\xady~\x1a\xc3\xa1D\x03B\x00\x04=\\(u\xc9\xbd\x11hu\xa7\x1a]\xb6L\xff\xcb\x139k\x16=\x03\x9b\x1d\x93'\x82H\x91\x80C4v\xa45**\xdd\x00\xe
b\xb0\xd5\xc9LQ[r\xeb\x10\xf1\xfd\x8f?\x03\xb4/J+%[\xfc\x9a\xa9\xe3"                                                                                          
>>>                                                                                                                                                           
```

**Comment by ofek** [comment]
Also I just confirmed it cannot load it.

**Comment by wbond** [comment]
Mind doing a debug via asn1crypto of both?

**Comment by ofek** [comment]
```
>>> der = private_key.private_bytes(encoding=Encoding.DER, format=PrivateFormat.PKCS8, encryption_algorithm=NoEncryption())                                   
>>> keys.PrivateKeyInfo.load(der).native                                                                                                                      
OrderedDict([('version', 0), ('private_key_algorithm', OrderedDict([('algorithm', 'ec'), ('parameters', '1.3.132.0.10')])), ('private_key', OrderedDict([('ver
sion', 'ecPrivkeyVer1'), ('private_key', 87993618360805341115891506172036624893404292644470266399436498750715784469187), ('parameters', None), ('public_key', 
b"\x04=\\(u\xc9\xbd\x11hu\xa7\x1a]\xb6L\xff\xcb\x139k\x16=\x03\x9b\x1d\x93'\x82H\x91\x80C4v\xa45**\xdd\x00\xeb\xb0\xd5\xc9LQ[r\xeb\x10\xf1\xfd\x8f?\x03\xb4/J+
%[\xfc\x9a\xa9\xe3")])), ('attributes', None)])                                                                                                               
>>>                                                                                                                                                           
```

**Comment by wbond** [comment]
Theres a `.debug()` method on all asn1crypto objects that dumps all the info that was parsed.

**Comment by ofek** [comment]
```
>>> keys.PrivateKeyInfo.load(der).debug()                                                                                                                     
  asn1crypto.keys.PrivateKeyInfo Object #233738872                                                                                                            
    Header: 0x308184                                                                                                                                          
      constructed universal tag 16                                                                                                                            
    Data: 0x020100301006072a8648ce3d020106052b8104000a046d306b0201010420c28a9f80738f770d527803a566cf6fc3edf6cea586c4fc4a5223a5ad797e1ac3a144034200043d5c2875c9
bd116875a71a5db64cffcb13396b163d039b1d932782489180433476a4352a2add00ebb0d5c94c515b72eb10f1fd8f3f03b42f4a2b255bfc9aa9e3                                        
      Field "version"                                                                                                                                         
        asn1crypto.core.Integer Object #253385136                                                                                                             
          Header: 0x0201                                                                                                                                      
            primitive universal tag 2                                                                                                                         
          Data: 0x00                                                                                                                                          
            Native: 0                                                                                                                                         
      Field "private_key_algorithm"                                                                                                                           
        asn1crypto.keys.PrivateKeyAlgorithm Object #253384856                                                                                                 
          Header: 0x3010                                                                                                                                      
            constructed universal tag 16                                                                                                                      
          Data: 0x06072a8648ce3d020106052b8104000a                                                                                                            
            Field "algorithm"                                                                                                                                 
              asn1crypto.keys.PrivateKeyAlgorithmId Object #253384968                                                                                         
                Header: 0x0607                                                                                                                                
                  primitive universal tag 6                                                                                                                   
                Data: 0x2a8648ce3d0201                                                                                                                        
                  Native: ec                                                                                                                                  
            Field "parameters"                                                                                                                                
              asn1crypto.keys.ECDomainParameters Object #253384800                                                                                            
                Data: 0x06052b8104000a                                                                                                                        
                  asn1crypto.keys.NamedCurve Object #253385024                                                                                                
                    Header: 0x0605                                                                                                                            
                      primitive universal tag 6                                                                                                               
                    Data: 0x2b8104000a                                                                                                                        
                      Native: 1.3.132.0.10                                                                                                                    
      Field "private_key"                                                                                                                                     
        asn1crypto.core.ParsableOctetString Object #253385248                                                                                                 
          Header: 0x046d                                                                                                                                      
            primitive universal tag 4                                                                                                                         
          Data: 0x306b0201010420c28a9f80738f770d527803a566cf6fc3edf6cea586c4fc4a5223a5ad797e1ac3a144034200043d5c2875c9bd116875a71a5db64cffcb13396b163d039b1d93
2782489180433476a4352a2add00ebb0d5c94c515b72eb10f1fd8f3f03b42f4a2b255bfc9aa9e3                                                                                
            asn1crypto.keys.ECPrivateKey Object #253385864                                                                                                    
              Header: 0x306b                                                                                                                                  
                constructed universal tag 16                                                                                                                  
              Data: 0x0201010420c28a9f80738f770d527803a566cf6fc3edf6cea586c4fc4a5223a5ad797e1ac3a144034200043d5c2875c9bd116875a71a5db64cffcb13396b163d039b1d93
2782489180433476a4352a2add00ebb0d5c94c515b72eb10f1fd8f3f03b42f4a2b255bfc9aa9e3                                                                                
                Field "version"                                                                                                                               
                  asn1crypto.keys.ECPrivateKeyVersion Object #253385976                                                                                       
                    Header: 0x0201                                                                                                                            
                      primitive universal tag 2                                                                                                               
                    Data: 0x01                                                                                                                                
                      Native: ecPrivkeyVer1                                                                                                                   
                Field "private_key"                                                                                                                           
                  asn1crypto.core.IntegerOctetString Object #253384632                                                                                        
                    Header: 0x0420                                                                                                                            
                      primitive universal tag 4                                                                                                               
                    Data: 0xc28a9f80738f770d527803a566cf6fc3edf6cea586c4fc4a5223a5ad797e1ac3                                                                  
                      Native: 87993618360805341115891506172036624893404292644470266399436498750715784469187                                                   
                Field "public_key"                                                                                                                            
                  asn1crypto.keys.ECPointBitString Object #253384912                                                                                          
                    Header: 0xa1440342                                                                                                                        
                      context tag 1 (explicitly tagged)                                                                                                       
                        primitive universal 3                                                                                                                 
                    Data: 0x00043d5c2875c9bd116875a71a5db64cffcb13396b163d039b1d932782489180433476a4352a2add00ebb0d5c94c515b72eb10f1fd8f3f03b42f4a2b255bfc9aa9
e3                                                                                                                                                            
                      Native: b"\x04=\\(u\xc9\xbd\x11hu\xa7\x1a]\xb6L\xff\xcb\x139k\x16=\x03\x9b\x1d\x93'\x82H\x91\x80C4v\xa45**\xdd\x00\xeb\xb0\xd5\xc9LQ[r\x
eb\x10\xf1\xfd\x8f?\x03\xb4/J+%[\xfc\x9a\xa9\xe3"                                                                                                             
>>>                                                                                                                                                           
```

**Comment by wbond** [comment]
How about the output from cryptography?

**Comment by ofek** [comment]
The DER?

```
b"0\x81\x84\x02\x01\x000\x10\x06\x07*\x86H\xce=\x02\x01\x06\x05+\x81\x04\x00\n\x04m0k\x02\x01\x01\x04 \xc2\x8a\x9f\x80s\x8fw\rRx\x03\xa5f\xcfo\xc3\xed\xf6\xce\xa5\x86\xc4\xfcJR#\xa5\xady~\x1a\xc3\xa1D\x03B\x00\x04=\\(u\xc9\xbd\x11hu\xa7\x1a]\xb6L\xff\xcb\x139k\x16=\x03\x9b\x1d\x93'\x82H\x91\x80C4v\xa45**\xdd\x00\xeb\xb0\xd5\xc9LQ[r\xeb\x10\xf1\xfd\x8f?\x03\xb4/J+%[\xfc\x9a\xa9\xe3"
```

**Comment by wbond** [comment]
No, the asn1crypto debug of the DER. Sorry!

**Comment by ofek** [comment]
Oh, that's what I debugged.

**Comment by wbond** [comment]
In that case, can you debug the one created by asn1crypto? :smile:

**Comment by ofek** [comment]
Thanks for your patience!

pyca/cryptography:
```
>>> openssl_der = private_key.private_bytes(encoding=Encoding.DER, format=PrivateFormat.PKCS8, encryption_algorithm=NoEncryption())                           
>>> keys.PrivateKeyInfo.load(openssl_der).debug()                                                                                                             
  asn1crypto.keys.PrivateKeyInfo Object #212753880                                                                                                            
    Header: 0x308184                                                                                                                                          
      constructed universal tag 16                                                                                                                            
    Data: 0x020100301006072a8648ce3d020106052b8104000a046d306b0201010420c28a9f80738f770d527803a566cf6fc3edf6cea586c4fc4a5223a5ad797e1ac3a144034200043d5c2875c9
bd116875a71a5db64cffcb13396b163d039b1d932782489180433476a4352a2add00ebb0d5c94c515b72eb10f1fd8f3f03b42f4a2b255bfc9aa9e3                                        
      Field "version"                                                                                                                                         
        asn1crypto.core.Integer Object #257996056                                                                                                             
          Header: 0x0201                                                                                                                                      
            primitive universal tag 2                                                                                                                         
          Data: 0x00                                                                                                                                          
            Native: 0                                                                                                                                         
      Field "private_key_algorithm"                                                                                                                           
        asn1crypto.keys.PrivateKeyAlgorithm Object #246297768                                                                                                 
          Header: 0x3010                                                                                                                                      
            constructed universal tag 16                                                                                                                      
          Data: 0x06072a8648ce3d020106052b8104000a                                                                                                            
            Field "algorithm"                                                                                                                                 
              asn1crypto.keys.PrivateKeyAlgorithmId Object #257995216                                                                                         
                Header: 0x0607                                                                                                                                
                  primitive universal tag 6                                                                                                                   
                Data: 0x2a8648ce3d0201                                                                                                                        
                  Native: ec                                                                                                                                  
            Field "parameters"                                                                                                                                
              asn1crypto.keys.ECDomainParameters Object #257996224                                                                                            
                Data: 0x06052b8104000a                                                                                                                        
                  asn1crypto.keys.NamedCurve Object #257996000                                                                                                
                    Header: 0x0605                                                                                                                            
                      primitive universal tag 6                                                                                                               
                    Data: 0x2b8104000a                                                                                                                        
                      Native: 1.3.132.0.10                                                                                                                    
      Field "private_key"                                                                                                                                     
        asn1crypto.core.ParsableOctetString Object #257996168                                                                                                 
          Header: 0x046d                                                                                                                                      
            primitive universal tag 4                                                                                                                         
          Data: 0x306b0201010420c28a9f80738f770d527803a566cf6fc3edf6cea586c4fc4a5223a5ad797e1ac3a144034200043d5c2875c9bd116875a71a5db64cffcb13396b163d039b1d93
2782489180433476a4352a2add00ebb0d5c94c515b72eb10f1fd8f3f03b42f4a2b255bfc9aa9e3                                                                                
            asn1crypto.keys.ECPrivateKey Object #257996336                                                                                                    
              Header: 0x306b                                                                                                                                  
                constructed universal tag 16                                                                                                                  
              Data: 0x0201010420c28a9f80738f770d527803a566cf6fc3edf6cea586c4fc4a5223a5ad797e1ac3a144034200043d5c2875c9bd116875a71a5db64cffcb13396b163d039b1d93
2782489180433476a4352a2add00ebb0d5c94c515b72eb10f1fd8f3f03b42f4a2b255bfc9aa9e3                                                                                
                Field "version"                                                                                                                               
                  asn1crypto.keys.ECPrivateKeyVersion Object #257996280                                                                                       
                    Header: 0x0201                                                                                                                            
                      primitive universal tag 2                                                                                                               
                    Data: 0x01                                                                                                                                
                      Native: ecPrivkeyVer1                                                                                                                   
                Field "private_key"                                                                                                                           
                  asn1crypto.core.IntegerOctetString Object #257996448                                                                                        
                    Header: 0x0420                                                                                                                            
                      primitive universal tag 4                                                                                                               
                    Data: 0xc28a9f80738f770d527803a566cf6fc3edf6cea586c4fc4a5223a5ad797e1ac3                                                                  
                      Native: 87993618360805341115891506172036624893404292644470266399436498750715784469187                                                   
                Field "public_key"                                                                                                                            
                  asn1crypto.keys.ECPointBitString Object #257995832                                                                                          
                    Header: 0xa1440342                                                                                                                        
                      context tag 1 (explicitly tagged)                                                                                                       
                        primitive universal 3                                                                                                                 
                    Data: 0x00043d5c2875c9bd116875a71a5db64cffcb13396b163d039b1d932782489180433476a4352a2add00ebb0d5c94c515b72eb10f1fd8f3f03b42f4a2b255bfc9aa9
e3                                                                                                                                                            
                      Native: b"\x04=\\(u\xc9\xbd\x11hu\xa7\x1a]\xb6L\xff\xcb\x139k\x16=\x03\x9b\x1d\x93'\x82H\x91\x80C4v\xa45**\xdd\x00\xeb\xb0\xd5\xc9LQ[r\x
eb\x10\xf1\xfd\x8f?\x03\xb4/J+%[\xfc\x9a\xa9\xe3"                                                                                                             
>>>                                                                                                                                                           
```

asn1crypto:
```
>>> pk = keys.ECPrivateKey({'version': 'ecPrivkeyVer1', 'private_key': 87993618360805341115891506172036624893404292644470266399436498750715784469187,'paramete
rs': keys.ECDomainParameters({'named': '1.3.132.0.10'}), 'public_key': keys.ECPointBitString.from_coords(27753912938952041417634381842191885283234814940840273
460372041880794577257268, 53663045980837260634637807506183816949039230809110041985901491152185762425315)})                                                    
>>> keys.PrivateKeyInfo({'version': 0, 'private_key_algorithm': keys.PrivateKeyAlgorithm({'algorithm': 'ec'}), 'private_key': pk}).debug()                    
  asn1crypto.keys.PrivateKeyInfo Object #257996000                                                                                                            
      constructed universal tag 16                                                                                                                            
    Data: 0x020100300906072a8648ce3d0201047630740201010420c28a9f80738f770d527803a566cf6fc3edf6cea586c4fc4a5223a5ad797e1ac3a00706052b8104000aa144034200043d5c28
75c9bd116875a71a5db64cffcb13396b163d039b1d932782489180433476a4352a2add00ebb0d5c94c515b72eb10f1fd8f3f03b42f4a2b255bfc9aa9e3                                    
      Field "version"                                                                                                                                         
        asn1crypto.core.Integer Object #257996280                                                                                                             
          Header: 0x0201                                                                                                                                      
            primitive universal tag 2                                                                                                                         
          Data: 0x00                                                                                                                                          
            Native: 0                                                                                                                                         
      Field "private_key_algorithm"                                                                                                                           
        asn1crypto.keys.PrivateKeyAlgorithm Object #239865360                                                                                                 
          Header: 0x3009                                                                                                                                      
            constructed universal tag 16                                                                                                                      
          Data: 0x06072a8648ce3d0201                                                                                                                          
            Field "algorithm"                                                                                                                                 
              asn1crypto.keys.PrivateKeyAlgorithmId Object #257996168                                                                                         
                Header: 0x0607                                                                                                                                
                  primitive universal tag 6                                                                                                                   
                Data: 0x2a8648ce3d0201                                                                                                                        
                  Native: ec                                                                                                                                  
      Field "private_key"                                                                                                                                     
        asn1crypto.core.ParsableOctetString Object #257995832                                                                                                 
          Header: 0x0476                                                                                                                                      
            primitive universal tag 4                                                                                                                         
          Data: 0x30740201010420c28a9f80738f770d527803a566cf6fc3edf6cea586c4fc4a5223a5ad797e1ac3a00706052b8104000aa144034200043d5c2875c9bd116875a71a5db64cffcb
13396b163d039b1d932782489180433476a4352a2add00ebb0d5c94c515b72eb10f1fd8f3f03b42f4a2b255bfc9aa9e3                                                              
            asn1crypto.keys.ECPrivateKey Object #257996504                                                                                                    
              Header: 0x3074                                                                                                                                  
                constructed universal tag 16                                                                                                                  
              Data: 0x0201010420c28a9f80738f770d527803a566cf6fc3edf6cea586c4fc4a5223a5ad797e1ac3a00706052b8104000aa144034200043d5c2875c9bd116875a71a5db64cffcb
13396b163d039b1d932782489180433476a4352a2add00ebb0d5c94c515b72eb10f1fd8f3f03b42f4a2b255bfc9aa9e3                                                              
                Field "version"                                                                                                                               
                  asn1crypto.keys.ECPrivateKeyVersion Object #257995216                                                                                       
                    Header: 0x0201                                                                                                                            
                      primitive universal tag 2                                                                                                               
                    Data: 0x01                                                                                                                                
                      Native: ecPrivkeyVer1                                                                                                                   
                Field "private_key"                                                                                                                           
                  asn1crypto.core.IntegerOctetString Object #257996560                                                                                        
                    Header: 0x0420                                                                                                                            
                      primitive universal tag 4                                                                                                               
                    Data: 0xc28a9f80738f770d527803a566cf6fc3edf6cea586c4fc4a5223a5ad797e1ac3                                                                  
                      Native: 87993618360805341115891506172036624893404292644470266399436498750715784469187                                                   
                Field "parameters"                                                                                                                            
                  asn1crypto.keys.ECDomainParameters Object #257996728                                                                                        
                    Header: 0xa007                                                                                                                            
                      context tag 0 (explicitly tagged)                                                                                                       
                    Data: 0x06052b8104000a                                                                                                                    
                      asn1crypto.keys.NamedCurve Object #257996672                                                                                            
                        Header: 0x0605                                                                                                                        
                          primitive universal tag 6                                                                                                           
                        Data: 0x2b8104000a                                                                                                                    
                          Native: 1.3.132.0.10                                                                                                                
                Field "public_key"                                                                                                                            
                  asn1crypto.keys.ECPointBitString Object #257996392                                                                                          
                    Header: 0xa1440342                                                                                                                        
                      context tag 1 (explicitly tagged)                                                                                                       
                        primitive universal 3                                                                                                                 
                    Data: 0x00043d5c2875c9bd116875a71a5db64cffcb13396b163d039b1d932782489180433476a4352a2add00ebb0d5c94c515b72eb10f1fd8f3f03b42f4a2b255bfc9aa9
e3                                                                                                                                                            
                      Native: b"\x04=\\(u\xc9\xbd\x11hu\xa7\x1a]\xb6L\xff\xcb\x139k\x16=\x03\x9b\x1d\x93'\x82H\x91\x80C4v\xa45**\xdd\x00\xeb\xb0\xd5\xc9LQ[r\x
eb\x10\xf1\xfd\x8f?\x03\xb4/J+%[\xfc\x9a\xa9\xe3"                                                                                                             
>>>                                                                                                                                                           
```

**Comment by wbond** [comment]
pyca/cryptography is adding the EC named curve parameters to the `private_key_algorithm`, whereas utilizing asn1crypto you did not.

**Comment by ofek** [comment]
Oh ok ty! What would that look like?

**Comment by wbond** [comment]
In the debug you'll see:

```
Field "parameters"                                                                                                                                
              asn1crypto.keys.ECDomainParameters Object #257996224                                                                                            
                Data: 0x06052b8104000a                                                                                                                        
                  asn1crypto.keys.NamedCurve Object #257996000                                                                                                
                    Header: 0x0605                                                                                                                            
                      primitive universal tag 6                                                                                                               
                    Data: 0x2b8104000a                                                                                                                        
                      Native: 1.3.132.0.10       
```

So an `ECDomainParameters`, like when constructing the `ECPrivateKey`.

You'll also notice they omit the `parameters` field from` ECPrivateKey`. Often times when a key is wrapped in PKCS#8, the parameters are "hoisted" up to the outer-most container. This may be covered by the RFC, I don't recall. Either way, a look at https://tools.ietf.org/html/rfc5208#page-3 is probably a good idea.

**Comment by ofek** [comment]
You're the best :)

```
>>> openssl_der = private_key.private_bytes(encoding=Encoding.DER, format=PrivateFormat.PKCS8, encryption_algorithm=NoEncryption())                           
>>> pk = keys.ECPrivateKey({'version': 'ecPrivkeyVer1', 'private_key': 87993618360805341115891506172036624893404292644470266399436498750715784469187, 'public_
key': keys.ECPointBitString(b"\x04=\\(u\xc9\xbd\x11hu\xa7\x1a]\xb6L\xff\xcb\x139k\x16=\x03\x9b\x1d\x93'\x82H\x91\x80C4v\xa45**\xdd\x00\xeb\xb0\xd5\xc9LQ[r\xeb
\x10\xf1\xfd\x8f?\x03\xb4/J+%[\xfc\x9a\xa9\xe3")})                                                                                                            
>>> asn1crypto_der = keys.PrivateKeyInfo({'version': 0, 'private_key_algorithm': keys.PrivateKeyAlgorithm({'algorithm': 'ec', 'parameters': keys.ECDomainParam
eters(name='named', value='1.3.132.0.10')}), 'private_key': pk}).dump()                                                                                       
>>> asn1crypto_der == openssl_der                                                                                                                             
True                                                                                                                                                          
>>>                                                                                                                                                           
```
