### ISSUE TITLE
Got errors while parsing

### ISSUE THREAD

**Issue by huytn** [wbond/asn1crypto#69]
Here is my code:

```
# -*- coding: utf-8 -*-

'''
Created on Aug 17, 2017

@author: huytn
'''
from asn1crypto import pem, x509
from certvalidator import CertificateValidator, ValidationContext, validate

if __name__ == '__main__':
    trust_roots = []
    with open('ca4.crt', 'rb') as f:
        ders_bytes = f.read()
        if pem.detect(ders_bytes):
            for _, _, der_bytes in pem.unarmor(ders_bytes, multiple=True):
                trust_roots.append(der_bytes)
        else:
            trust_roots.append(ders_bytes)
        f.close()
    
    with open('cert.pem', 'rb') as f:
        end_entity_cert = f.read()
        if pem.detect(end_entity_cert):
            _, _, end_entity_cert = pem.unarmor(end_entity_cert)
        f.close()
    
    context = ValidationContext(trust_roots=trust_roots, allow_fetching=True, ocsp_fetch_params={'hash_algo':u'sha256'}, revocation_mode='require')
    validator = CertificateValidator(end_entity_cert, validation_context=context)
    valid_path = validator.validate_usage(validator._certificate.key_usage_value.native, set(validator._certificate.extended_key_usage_value.native))
    result = validate.validate_path(context, valid_path)
```

ca4.crt file includes root and CA, below is output

```
Traceback (most recent call last):
  File "test_ocsp.py", line 32, in <module>
    valid_path = validator.validate_usage(validator._certificate.key_usage_value.native, set(validator._certificate.extended_key_usage_value.native))
  File "/Users/huytn/.pyenv/versions/2.7.13/lib/python2.7/site-packages/certvalidator/__init__.py", line 193, in validate_usage
    self._validate_path()
  File "/Users/huytn/.pyenv/versions/2.7.13/lib/python2.7/site-packages/certvalidator/__init__.py", line 121, in _validate_path
    validate_path(self._context, candidate_path)
  File "/Users/huytn/.pyenv/versions/2.7.13/lib/python2.7/site-packages/certvalidator/validate.py", line 50, in validate_path
    return _validate_path(validation_context, path)
  File "/Users/huytn/.pyenv/versions/2.7.13/lib/python2.7/site-packages/certvalidator/validate.py", line 386, in _validate_path
    end_entity_name_override=end_entity_name_override
  File "/Users/huytn/.pyenv/versions/2.7.13/lib/python2.7/site-packages/certvalidator/validate.py", line 891, in verify_ocsp_response
    ocsp_responses = validation_context.retrieve_ocsps(cert, issuer)
  File "/Users/huytn/.pyenv/versions/2.7.13/lib/python2.7/site-packages/certvalidator/context.py", line 507, in retrieve_ocsps
    self._extract_ocsp_certs(ocsp_response)
  File "/Users/huytn/.pyenv/versions/2.7.13/lib/python2.7/site-packages/certvalidator/context.py", line 534, in _extract_ocsp_certs
    if self.certificate_registry.add_other_cert(other_cert):
  File "/Users/huytn/.pyenv/versions/2.7.13/lib/python2.7/site-packages/certvalidator/registry.py", line 199, in add_other_cert
    if cert.key_identifier:
  File "/Users/huytn/.pyenv/versions/2.7.13/lib/python2.7/site-packages/asn1crypto/x509.py", line 2250, in key_identifier
    if not self.key_identifier_value:
  File "/Users/huytn/.pyenv/versions/2.7.13/lib/python2.7/site-packages/asn1crypto/x509.py", line 1931, in key_identifier_value
    self._set_extensions()
  File "/Users/huytn/.pyenv/versions/2.7.13/lib/python2.7/site-packages/asn1crypto/x509.py", line 1885, in _set_extensions
    setattr(self, attribute_name, extension['extn_value'].parsed)
  File "/Users/huytn/.pyenv/versions/2.7.13/lib/python2.7/site-packages/asn1crypto/core.py", line 3205, in __getitem__
    raise e
ValueError: Insufficient data - 2 bytes requested but only 0 available
    while parsing asn1crypto.core.ParsableOctetString
    while parsing asn1crypto.x509.Extension
```

**Comment by joernheissler** [comment]
Can you attach your certs?

**Comment by joernheissler** [comment]
And make sure the test case can be tested and matches your traceback? There is no line 32 in your code.

**Comment by huytn** [comment]
OK @joernheissler, I updated 

[Archive.zip](https://github.com/wbond/asn1crypto/files/1245028/Archive.zip)
Attached file includes ca4.crt and cert.pem

**Comment by joernheissler** [comment]
There's an incorrect cert involved. I assume it's downloaded by the code for OCSP validation or sth, attached it here:
[hightrusted.zip](https://github.com/wbond/asn1crypto/files/1245147/hightrusted.zip)

Here is the hex dump of the incorrect extension: 30 0d 06 09 2b 06 01 05 05 07 30 01 05 04 00
rfc6960 defines the syntax as:
ext-ocsp-nocheck EXTENSION ::= { SYNTAX NULL IDENTIFIED
                                 BY id-pkix-ocsp-nocheck }

You've got an empty octet string (04 00) instead of an octet string encapsulating NULL (04 02 05 00).

**Comment by huytn** [comment]
As I know this ocsp certificate is generated by Window CA.

**Comment by joernheissler** [comment]
Looks like ejbca to me.

**Comment by huytn** [comment]
Thanks you, I fixed this issue
